.segment "PDATAENEMYNAMES"

ff6_enemy_names:
.byte $86, $ae, $9a, $ab, $9d, $ff, $ff, $ff, $ff, $ff
.byte $88, $a6, $a9, $9e, $ab, $a2, $9a, $a5, $ff, $92
.byte $93, $9e, $a6, $a9, $a5, $9a, $ab, $ff, $ff, $ff
.byte $8d, $a2, $a7, $a3, $9a, $ff, $ff, $ff, $ff, $ff
.byte $92, $9a, $a6, $ae, $ab, $9a, $a2, $ff, $ff, $ff
.byte $81, $a8, $ab, $a0, $a1, $9e, $ac, $9e, $ff, $ff
.byte $8c, $9a, $a0, $a7, $9a, $ff, $91, $c5, $ff, $ff
.byte $98, $a8, $a3, $a2, $a6, $9b, $a8, $ff, $ff, $ff
.byte $82, $a5, $a8, $ae, $9d, $ff, $ff, $ff, $ff, $ff
.byte $8c, $a2, $ac, $ad, $b2, $ff, $ff, $ff, $ff, $ff
.byte $80, $a5, $ff, $89, $9a, $9b, $ab, $ff, $ff, $ff
.byte $99, $9a, $a0, $a1, $ab, $9e, $a6, $ff, $ff, $ff
.byte $80, $a9, $a8, $9c, $ab, $b2, $a9, $a1, $9a, $ff
.byte $83, $9a, $ab, $a4, $ff, $85, $a8, $ab, $9c, $9e
.byte $80, $a7, $a0, $9e, $a5, $ff, $96, $c5, $ff, $ff
.byte $8e, $af, $9e, $ab, $ac, $a8, $ae, $a5, $ff, $ff
.byte $92, $a4, $9e, $a5, $9e, $ad, $9a, $a5, $ff, $ff
.byte $82, $a8, $a6, $a6, $9a, $a7, $9d, $9e, $ab, $ff
.byte $8c, $ae, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
.byte $96, $9e, $ab, $9e, $ab, $9a, $ad, $ff, $ff, $ff
.byte $8c, $ae, $a0, $9b, $9e, $9a, $ab, $ff, $ff, $ff
.byte $81, $9e, $a5, $a6, $a8, $9d, $9a, $ab, $ff, $ff
.byte $8c, $ae, $ae, $9d, $ff, $92, $ae, $ae, $9d, $ff
.byte $8b, $9e, $9a, $9f, $ff, $81, $ae, $a7, $a7, $b2
.byte $92, $ad, $ab, $9a, $b2, $ff, $82, $9a, $ad, $ff
.byte $92, $a2, $a5, $af, $9e, $ab, $ff, $8b, $c5, $ff
.byte $83, $a8, $9b, $9e, $ab, $a6, $9a, $a7, $ff, $ff
.byte $8c, $9e, $a0, $9a, $a5, $a8, $9d, $a8, $ad, $a1
.byte $85, $a2, $9d, $a8, $ab, $ff, $ff, $ff, $ff, $ff
.byte $81, $ab, $a2, $9a, $ab, $9e, $ae, $ac, $ff, $ff
.byte $92, $ae, $ab, $a2, $9a, $a7, $9d, $9e, $ab, $ff
.byte $82, $a1, $a2, $a6, $9e, $ab, $9a, $ff, $ff, $ff
.byte $81, $9e, $a1, $9e, $a6, $a8, $ad, $a1, $ff, $ff
.byte $85, $9a, $9f, $a7, $a2, $ab, $ff, $ff, $ff, $ff
.byte $8b, $9e, $ac, $ac, $9e, $ab, $ff, $8b, $c5, $ff
.byte $85, $a8, $ac, $ac, $a2, $a5, $ff, $83, $c5, $ff
.byte $87, $a8, $a5, $b2, $ff, $83, $c5, $ff, $ff, $ff
.byte $85, $a2, $9e, $a7, $9d, $ff, $83, $c5, $ff, $ff
.byte $81, $ab, $9a, $9c, $a1, $a2, $a8, $c5, $ff, $ff
.byte $93, $b2, $ab, $9a, $a7, $a7, $a8, $c5, $ff, $ff
.byte $83, $9a, $ab, $a4, $b0, $a2, $a7, $9d, $ff, $ff
.byte $80, $9e, $a9, $b2, $a8, $ab, $a7, $a2, $ac, $ff
.byte $95, $ae, $a5, $ad, $ae, $ab, $9e, $ff, $ff, $ff
.byte $95, $9a, $ac, $9e, $a0, $a2, $9a, $ad, $ad, $9a
.byte $99, $a8, $a4, $a4, $9a, $ff, $ff, $ff, $ff, $ff
.byte $93, $ab, $9a, $a9, $a9, $9e, $ab, $ff, $ff, $ff
.byte $87, $a8, $ab, $a7, $9e, $ad, $ff, $ff, $ff, $ff
.byte $8d, $9e, $ad, $ad, $a5, $9e, $c5, $ff, $ff, $ff
.byte $83, $9e, $a5, $ad, $9a, $ff, $81, $c5, $ff, $ff
.byte $8a, $a2, $a5, $a5, $9e, $ab, $ff, $8c, $c5, $ff
.byte $93, $ab, $a2, $a5, $a5, $a2, $ae, $a6, $ff, $ff
.byte $91, $9a, $9f, $9f, $a5, $9e, $ac, $a2, $9a, $ff
.byte $93, $ae, $a6, $9b, $a5, $9e, $b0, $9e, $9e, $9d
.byte $95, $9a, $a6, $a9, $a2, $ab, $9e, $ff, $93, $c5
.byte $82, $9a, $ab, $ad, $9a, $a0, $ab, $9a, $ff, $ff
.byte $92, $a2, $9e, $a0, $9f, $ab, $a2, $9e, $9d, $ff
.byte $8d, $9a, $ae, $ad, $a2, $a5, $a8, $a2, $9d, $ff
.byte $84, $b1, $a8, $9c, $a2, $ad, $9e, $ff, $ff, $ff
.byte $80, $a7, $a0, $ae, $a2, $9f, $a8, $ab, $a6, $ff
.byte $8b, $9e, $9a, $a9, $ff, $85, $ab, $a8, $a0, $ff
.byte $8b, $a2, $b3, $9a, $ab, $9d, $ff, $ff, $ff, $ff
.byte $8b, $a2, $ad, $b0, $a8, $ab, $ff, $82, $c5, $ff
.byte $92, $a5, $9a, $a0, $b0, $a8, $ab, $a6, $ff, $ff
.byte $87, $9e, $a5, $a5, $c3, $ac, $ff, $91, $c5, $ff
.byte $93, $b2, $a9, $a1, $a8, $a7, $ff, $ff, $ff, $ff
.byte $8e, $a7, $a2, $a8, $a7, $ff, $8a, $c5, $ff, $ff
.byte $8c, $9a, $a0, $a2, $ad, $9e, $a4, $ff, $80, $c5
.byte $92, $a4, $b2, $ff, $80, $ab, $a6, $a8, $ab, $ff
.byte $92, $9a, $ad, $9e, $a5, $a5, $a2, $ad, $9e, $ff
.byte $80, $ab, $a6, $a8, $ab, $9e, $9d, $ff, $96, $c5
.byte $92, $a9, $ab, $a2, $ad, $b3, $9e, $ab, $ff, $ff
.byte $85, $a5, $9a, $a7, $ff, $ff, $ff, $ff, $ff, $ff
.byte $8e, $ae, $ad, $9c, $9a, $ac, $ad, $ff, $ff, $ff
.byte $87, $ae, $a6, $a9, $ad, $b2, $ff, $ff, $ff, $ff
.byte $81, $ab, $9a, $a2, $a7, $a9, $9a, $a7, $ff, $ff
.byte $82, $ab, $ae, $a5, $a5, $9e, $ab, $ff, $ff, $ff
.byte $82, $9a, $9c, $ad, $ae, $9a, $ab, $ff, $ff, $ff
.byte $81, $9a, $a7, $9d, $a2, $ad, $ff, $ff, $ff, $ff
.byte $87, $9a, $ab, $af, $9e, $ac, $ad, $9e, $ab, $ff
.byte $81, $a8, $a6, $9b, $ff, $ff, $ff, $ff, $ff, $ff
.byte $92, $ad, $a2, $a5, $a5, $ff, $8b, $a2, $9f, $9e
.byte $8b, $ae, $a7, $9a, $ad, $b2, $ac, $ff, $ff, $ff
.byte $95, $9e, $a2, $a5, $ff, $83, $c5, $ff, $ff, $ff
.byte $87, $a2, $a5, $a5, $ff, $86, $a2, $a0, $9a, $ac
.byte $93, $a8, $a7, $9b, $9e, $ab, $ab, $b2, $ff, $ff
.byte $8c, $9a, $a0, $a2, $9c, $ff, $94, $ab, $a7, $ff
.byte $8c, $a8, $af, $9e, $ab, $ff, $ff, $ff, $ff, $ff
.byte $85, $a2, $a0, $9a, $ab, $a8, $ff, $8b, $c5, $ff
.byte $83, $9e, $af, $a8, $9a, $a1, $9a, $a7, $ff, $ff
.byte $80, $ac, $a9, $a2, $ab, $9a, $a7, $ff, $ff, $ff
.byte $86, $a1, $a8, $ac, $ad, $ff, $ff, $ff, $ff, $ff
.byte $82, $ab, $9a, $b0, $a5, $9e, $ab, $ff, $ff, $ff
.byte $92, $9a, $a7, $9d, $ff, $91, $9a, $b2, $ff, $ff
.byte $80, $a5, $9a, $9c, $ab, $9a, $a7, $ff, $ff, $ff
.byte $80, $9c, $ad, $9a, $a7, $9e, $a8, $a7, $ff, $ff
.byte $92, $9a, $a7, $9d, $a1, $a8, $ab, $ac, $9e, $ff
.byte $83, $9a, $ab, $a4, $ac, $a2, $9d, $9e, $ff, $ff
.byte $8c, $9a, $a5, $9b, $a8, $ab, $a8, $ff, $ff, $ff
.byte $94, $ab, $a8, $a4, $ff, $ff, $ff, $ff, $ff, $ff
.byte $85, $a8, $a9, $9e, $ab, $ff, $ff, $ff, $ff, $ff
.byte $86, $ae, $9a, $ab, $9d, $ff, $8b, $c5, $ff, $ff
.byte $82, $a8, $ab, $a9, $a8, $ab, $9a, $a5, $ff, $ff
.byte $86, $9e, $a7, $9e, $ab, $9a, $a5, $ff, $ff, $ff
.byte $82, $a8, $af, $9e, $ab, $ad, $ff, $ff, $ff, $ff
.byte $8a, $9a, $a6, $ae, $a2, $ff, $ff, $ff, $ff, $ff
.byte $96, $9a, $ab, $a5, $a8, $9c, $a4, $ff, $ff, $ff
.byte $82, $a1, $9e, $ab, $ab, $b2, $ff, $ff, $ff, $ff
.byte $89, $a8, $a4, $9e, $ab, $ff, $ff, $ff, $ff, $ff
.byte $88, $ab, $a8, $a7, $ff, $85, $a2, $ac, $ad, $ff
.byte $83, $9e, $af, $a8, $9a, $a1, $9a, $a7, $ff, $ff
.byte $8f, $ab, $a8, $af, $a8, $a4, $9e, $ab, $ff, $ff
.byte $82, $a5, $a8, $ae, $9d, $b0, $ab, $c5, $ff, $ff
.byte $8c, $9a, $a1, $9a, $9d, $9e, $af, $9a, $ff, $ff
.byte $95, $9e, $9c, $ad, $a8, $ab, $ff, $87, $c5, $ff
.byte $8f, $9e, $9e, $a9, $9e, $ab, $ff, $ff, $ff, $ff
.byte $92, $9e, $b0, $9e, $ab, $ff, $91, $9a, $ad, $ff
.byte $92, $a8, $ab, $9a, $ad, $a1, $ff, $ff, $ff, $ff
.byte $83, $9e, $ac, $ad, $ab, $a8, $b2, $9e, $ab, $ff
.byte $82, $a1, $a2, $a9, $a9, $a2, $c5, $ff, $ff, $ff
.byte $82, $a8, $9e, $ae, $ab, $a5, $ff, $82, $9a, $ad
.byte $81, $a5, $a8, $a8, $9d, $9f, $9a, $a7, $a0, $ff
.byte $87, $ae, $a7, $ad, $a2, $a7, $a0, $ff, $87, $c5
.byte $86, $a8, $ab, $a0, $a2, $9a, $ac, $ff, $ff, $ff
.byte $83, $a8, $a7, $ff, $ff, $ff, $ff, $ff, $ff, $ff
.byte $8c, $ae, $ab, $ae, $ac, $ac, $ae, $ff, $ff, $ff
.byte $96, $9a, $ab, $ad, $a9, $ae, $9c, $a4, $ff, $ff
.byte $86, $a8, $ab, $a0, $a2, $a6, $9e, $ab, $9a, $ff
.byte $81, $9e, $a1, $9e, $a6, $a8, $ad, $a1, $ff, $8a
.byte $95, $9e, $9c, $ad, $a8, $ab, $ff, $8b, $c5, $ff
.byte $96, $b2, $af, $9e, $ab, $a7, $ff, $ff, $ff, $ff
.byte $99, $a8, $a6, $9b, $a2, $9e, $ff, $83, $c5, $ff
.byte $83, $ab, $9a, $a0, $a8, $a7, $ff, $ff, $ff, $ff
.byte $8f, $ab, $a2, $a6, $9e, $af, $9a, $a5, $ff, $83
.byte $96, $9e, $ab, $9e, $9d, $ab, $9a, $a0, $a8, $a7
.byte $82, $a2, $ab, $a9, $a2, $ae, $ac, $ff, $ff, $ff
.byte $92, $a9, $ab, $a2, $a7, $ad, $9e, $ab, $ff, $ff
.byte $8b, $9e, $a7, $9e, $ab, $a0, $a2, $9a, $ff, $ff
.byte $8c, $9a, $ab, $9c, $a1, $a8, $ac, $a2, $9a, $ac
.byte $86, $a5, $a8, $a8, $a6, $b0, $a2, $a7, $9d, $ff
.byte $83, $ab, $a8, $a9, $a9, $9e, $ab, $ff, $ff, $ff
.byte $91, $a8, $9c, $a4, $ff, $96, $9a, $ac, $a9, $ff
.byte $86, $ab, $9a, $ac, $ac, $b0, $b2, $ab, $a6, $ff
.byte $8b, $ae, $ab, $a2, $9d, $9a, $a7, $ff, $ff, $ff
.byte $93, $b0, $a2, $a7, $ac, $9c, $b2, $ad, $a1, $9e
.byte $8f, $9a, $ab, $9a, $a5, $9a, $9d, $a2, $9a, $ff
.byte $84, $b1, $a8, $ab, $9a, $b2, $ff, $ff, $ff, $ff
.byte $82, $ab, $ae, $ac, $a1, $9e, $ab, $ff, $ff, $ff
.byte $8e, $ae, $ab, $a8, $9b, $a8, $ab, $a8, $ac, $ff
.byte $80, $9c, $ab, $a8, $a9, $a1, $a2, $9e, $ac, $ff
.byte $92, $9c, $a1, $a6, $a2, $9d, $ad, $ff, $ff, $ff
.byte $83, $9e, $af, $a8, $ae, $ab, $9e, $ab, $ff, $ff
.byte $82, $9a, $a7, $9c, $9e, $ab, $ff, $ff, $ff, $ff
.byte $86, $a2, $a0, $9a, $a7, $ad, $a8, $9a, $9d, $ff
.byte $81, $9a, $ac, $a2, $a5, $a2, $ac, $a4, $ff, $ff
.byte $8c, $9e, $9d, $ae, $ac, $9a, $ff, $82, $c5, $ff
.byte $8b, $9a, $a7, $9d, $b0, $a8, $ab, $a6, $ff, $ff
.byte $93, $9e, $ac, $ad, $ff, $91, $a2, $9d, $9e, $ab
.byte $8f, $a5, $ae, $ad, $a8, $ff, $80, $c5, $ff, $ff
.byte $8e, $a7, $a2, $a8, $a7, $ff, $83, $c5, $ff, $ff
.byte $87, $9e, $9a, $af, $b2, $ff, $80, $c5, $ff, $ff
.byte $82, $a1, $9a, $ac, $9e, $ab, $ff, $ff, $ff, $ff
.byte $86, $9a, $a6, $a6, $9a, $ff, $ff, $ff, $ff, $ff
.byte $8f, $a8, $a9, $a5, $a2, $ae, $a6, $ff, $ff, $ff
.byte $88, $a7, $ad, $9a, $a7, $a0, $a2, $ab, $ff, $ff
.byte $8c, $a2, $ac, $9f, $a2, $ad, $ff, $ff, $ff, $ff
.byte $82, $ab, $9e, $9a, $ad, $ae, $ab, $9e, $ff, $ff
.byte $84, $a7, $ae, $a8, $ff, $ff, $ff, $ff, $ff, $ff
.byte $83, $9e, $9e, $a9, $9e, $b2, $9e, $ff, $ff, $ff
.byte $94, $a7, $ac, $9e, $9e, $a5, $a2, $9e, $ff, $ff
.byte $8d, $9e, $9c, $a4, $ff, $87, $c5, $ff, $ff, $ff
.byte $86, $ab, $9e, $a7, $9a, $9d, $9e, $ff, $ff, $ff
.byte $80, $a5, $a5, $ae, $ab, $a2, $a7, $a0, $ff, $91
.byte $8f, $9a, $a7, $9d, $a8, $ab, $9a, $ff, $ff, $ff
.byte $81, $a5, $9a, $9d, $9e, $ff, $83, $c5, $ff, $ff
.byte $86, $a2, $a0, $9a, $a7, $ad, $a8, $ac, $ff, $ff
.byte $8c, $9a, $a0, $a7, $9a, $ff, $91, $c5, $ff, $ff
.byte $8b, $b2, $9c, $9a, $a8, $a7, $ff, $ff, $ff, $ff
.byte $8f, $9a, $ab, $9a, $ac, $a2, $ad, $9e, $ff, $ff
.byte $8b, $9a, $a7, $9d, $ff, $91, $9a, $b2, $ff, $ff
.byte $80, $a7, $ad, $9a, $ab, $9e, $ac, $ff, $ff, $ff
.byte $80, $a7, $9e, $a6, $a8, $a7, $9e, $ff, $ff, $ff
.byte $8c, $a8, $a8, $a7, $9f, $a8, $ab, $a6, $ff, $ff
.byte $92, $a9, $9e, $9c, $ad, $ab, $9e, $ff, $ff, $ff
.byte $86, $ab, $9e, $9a, $ad, $ff, $8c, $c5, $ff, $ff
.byte $81, $a8, $a7, $a7, $9a, $9c, $a8, $a7, $ff, $ff
.byte $8e, $9c, $9e, $9a, $a7, $ae, $ac, $ff, $ff, $ff
.byte $8b, $a2, $af, $a2, $a7, $a0, $ff, $83, $c5, $ff
.byte $83, $9e, $9a, $ad, $a1, $ff, $96, $c5, $ff, $ff
.byte $85, $9a, $9c, $9e, $ff, $ff, $ff, $ff, $ff, $ff
.byte $8e, $ae, $ad, $ac, $a2, $9d, $9e, $ab, $ff, $ff
.byte $82, $a8, $9c, $a8, $ff, $ff, $ff, $ff, $ff, $ff
.byte $99, $9e, $af, $9e, $9a, $a4, $ff, $ff, $ff, $ff
.byte $8d, $a2, $a0, $a1, $ad, $b0, $9a, $a5, $a4, $c5
.byte $83, $9e, $a6, $a8, $a7, $ff, $8a, $c5, $ff, $ff
.byte $88, $a6, $a9, $9e, $ab, $a2, $9a, $a5, $ff, $84
.byte $83, $9e, $ac, $9e, $ab, $ad, $ff, $87, $c5, $ff
.byte $96, $a2, $b3, $9a, $ab, $9d, $ff, $ff, $ff, $ff
.byte $83, $9e, $af, $a2, $a5, $ff, $85, $a2, $ac, $ad
.byte $88, $a5, $a5, $ae, $b2, $9a, $a7, $a4, $9a, $ac
.byte $92, $9e, $ab, $a0, $9e, $9a, $a7, $ad, $ff, $ff
.byte $80, $ac, $a9, $a2, $9d, $a8, $9c, $a1, $c5, $ff
.byte $8a, $a7, $a8, $ad, $ad, $b2, $ff, $ff, $ff, $ff
.byte $8b, $ae, $a7, $9a, $ff, $96, $a8, $a5, $9f, $ff
.byte $81, $9e, $a5, $b3, $9e, $9c, $ae, $9e, $ff, $ff
.byte $82, $9a, $a5, $9a, $9d, $ab, $a2, $ae, $ac, $ff
.byte $93, $b3, $9a, $a4, $a6, $9a, $aa, $a2, $9e, $a5
.byte $8b, $ae, $a4, $a1, $9a, $af, $a2, $ff, $ff, $ff
.byte $84, $ae, $a4, $9a, $ab, $b2, $a8, $ad, $9e, $ff
.byte $8b, $9a, $a7, $9d, $ff, $86, $c5, $ff, $ff, $ff
.byte $86, $a8, $9e, $ad, $a2, $9a, $ff, $ff, $ff, $ff
.byte $86, $ab, $9e, $9a, $ad, $9e, $ab, $ff, $8c, $c5
.byte $81, $a8, $a0, $b2, $ff, $ff, $ff, $ff, $ff, $ff
.byte $8f, $ae, $ab, $ae, $ac, $9a, $ff, $ff, $ff, $ff
.byte $81, $a5, $9a, $9c, $a4, $ff, $83, $c5, $ff, $ff
.byte $80, $9d, $9a, $a6, $9a, $a7, $a4, $9a, $ab, $b2
.byte $83, $9a, $a7, $ad, $9e, $ff, $ff, $ff, $ff, $ff
.byte $8f, $a5, $9a, $ad, $a2, $a7, $ae, $a6, $ff, $83
.byte $83, $ae, $9e, $a5, $ff, $80, $ab, $a6, $a8, $ab
.byte $8f, $ac, $b2, $9c, $a1, $a8, $ac, $ff, $ff, $ff
.byte $8c, $a8, $ae, $ac, $ac, $9e, $ff, $ff, $ff, $ff
.byte $92, $a1, $9a, $a6, $9b, $a5, $a2, $a7, $a0, $ff
.byte $8f, $ae, $a7, $a2, $ac, $a1, $9e, $ab, $ff, $ff
.byte $81, $9a, $a5, $a5, $a8, $a8, $a7, $ff, $ff, $ff
.byte $86, $a8, $9b, $9b, $a5, $9e, $9d, $b2, $c5, $ff
.byte $86, $ab, $9e, $9a, $ad, $ff, $81, $c5, $ff, $ff
.byte $92, $9c, $a8, $ab, $a9, $a2, $a8, $a7, $ff, $ff
.byte $82, $a1, $9a, $a8, $ac, $ff, $83, $c5, $ff, $ff
.byte $92, $a9, $a2, $ad, $9f, $a2, $ab, $9e, $ff, $ff
.byte $95, $9e, $9c, $ad, $a8, $ab, $ff, $82, $c5, $ff
.byte $8b, $a2, $9c, $a1, $ff, $ff, $ff, $ff, $ff, $ff
.byte $91, $ae, $a4, $a1, $ff, $ff, $ff, $ff, $ff, $ff
.byte $8c, $9a, $a0, $a7, $9a, $ff, $91, $c5, $ff, $ff
.byte $81, $ae, $a0, $ff, $ff, $ff, $ff, $ff, $ff, $ff
.byte $92, $9e, $9a, $9f, $a5, $a8, $b0, $9e, $ab, $ff
.byte $85, $a8, $ab, $ad, $a2, $ac, $ff, $ff, $ff, $ff
.byte $95, $9e, $a7, $a8, $9b, $9e, $a7, $a7, $ae, $ff
.byte $86, $9a, $a5, $b2, $a9, $9d, $9e, $ac, $ff, $ff
.byte $89, $ae, $a7, $a4, $ff, $ff, $ff, $ff, $ff, $ff
.byte $8c, $9a, $a7, $9d, $ab, $9a, $a4, $9e, $ff, $ff
.byte $95, $9a, $a5, $9e, $a8, $ab, $ff, $ff, $ff, $ff
.byte $80, $a6, $9d, $ae, $ac, $9c, $a2, $9a, $ac, $ff
.byte $8d, $9e, $9c, $ab, $a8, $c5, $ff, $ff, $ff, $ff
.byte $86, $a5, $9a, $ac, $b2, $9a, $ff, $8b, $c5, $ff
.byte $8c, $9a, $a0, $a7, $9a, $ff, $91, $c5, $ff, $ff
.byte $96, $a2, $a5, $9d, $ff, $91, $9a, $ad, $ff, $ff
.byte $86, $a8, $a5, $9d, $ff, $81, $9e, $9a, $ab, $ff
.byte $88, $a7, $a7, $a8, $92, $9e, $a7, $ad, $ff, $ff
.byte $82, $a5, $b2, $a6, $9e, $a7, $ae, $ac, $ff, $ff
.byte $86, $9a, $ab, $a6, $ff, $ff, $ff, $ff, $ff, $ff
.byte $83, $9a, $9e, $9d, $9a, $a5, $ae, $ac, $ff, $ff
.byte $81, $9a, $9a, $a5, $b3, $9e, $a9, $a1, $a8, $a7
.byte $80, $a1, $ab, $a2, $a6, $9a, $a7, $ff, $ff, $ff
.byte $83, $9e, $9a, $ad, $a1, $ff, $8c, $c5, $ff, $ff
.byte $8c, $9e, $ad, $9a, $a5, $ff, $87, $c5, $ff, $ff
.byte $88, $a8, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
.byte $93, $a8, $a7, $9b, $9e, $ab, $ab, $a2, $9e, $ac
.byte $98, $a6, $a2, $ab, $ff, $ff, $ff, $ff, $ff, $ff
.byte $80, $a7, $a0, $a5, $9e, $ab, $ff, $96, $c5, $ff
.byte $8c, $9e, $a0, $9a, $ff, $80, $ab, $a6, $a8, $ab
.byte $95, $9a, $ab, $a0, $9a, $ac, $ff, $ff, $ff, $ff
.byte $93, $ae, $a7, $a7, $9e, $a5, $ff, $80, $c5, $ff
.byte $8f, $ab, $a8, $a6, $9e, $ad, $a1, $9e, $ae, $ac
.byte $8f, $a1, $9a, $a7, $ad, $a8, $a6, $ff, $93, $c5
.byte $83, $9a, $9d, $9a, $a5, $ae, $a6, $9a, $ff, $ff
.byte $92, $a1, $a2, $af, $9a, $ff, $ff, $ff, $ff, $ff
.byte $88, $9f, $ab, $a2, $ad, $ff, $ff, $ff, $ff, $ff
.byte $8d, $ae, $a6, $9b, $9e, $ab, $ff, $b4, $b6, $b8
.byte $8d, $ae, $a6, $9b, $9e, $ab, $ff, $b5, $b6, $bc
.byte $88, $a7, $9f, $9e, $ab, $a7, $a8, $ff, $ff, $ff
.byte $82, $ab, $9a, $a7, $9e, $ff, $ff, $ff, $ff, $ff
.byte $82, $ab, $9a, $a7, $9e, $ff, $ff, $ff, $ff, $ff
.byte $94, $a6, $9a, $ab, $a8, $ff, $ff, $ff, $ff, $ff
.byte $94, $a6, $9a, $ab, $a8, $ff, $ff, $ff, $ff, $ff
.byte $86, $ae, $9a, $ab, $9d, $a2, $9a, $a7, $ff, $ff
.byte $86, $ae, $9a, $ab, $9d, $a2, $9a, $a7, $ff, $ff
.byte $80, $a2, $ab, $ff, $85, $a8, $ab, $9c, $9e, $ff
.byte $95, $9a, $a5, $a2, $a0, $9a, $ab, $c5, $ff, $ff
.byte $95, $9a, $a5, $a2, $a0, $9a, $ab, $c5, $ff, $ff
.byte $85, $a5, $9a, $a6, $9e, $ff, $84, $c5, $ff, $ff
.byte $94, $a5, $ad, $a2, $a6, $9a, $ff, $96, $c5, $ff
.byte $8d, $9e, $a5, $9a, $a9, $9a, $ff, $ff, $ff, $ff
.byte $81, $9e, $a1, $9e, $a6, $a8, $ad, $a1, $ff, $8a
.byte $8a, $9e, $9f, $a4, $9a, $ff, $ff, $ff, $ff, $ff
.byte $93, $9e, $a7, $ad, $9a, $9c, $a5, $9e, $ff, $ff
.byte $83, $ae, $a5, $a5, $9a, $a1, $9a, $a7, $ff, $ff
.byte $83, $9e, $9a, $ad, $a1, $a0, $9a, $b3, $9e, $ff
.byte $82, $a1, $9a, $9d, $9a, $ab, $a7, $a8, $a8, $a4
.byte $82, $ae, $ab, $a5, $9a, $b1, $ff, $ff, $ff, $ff
.byte $8b, $9a, $ab, $9a, $a0, $a8, $ab, $a7, $ff, $ff
.byte $8c, $a8, $9e, $9b, $a2, $ae, $ac, $ff, $ff, $ff
.byte $96, $ab, $9e, $b1, $ac, $a8, $ae, $a5, $ff, $ff
.byte $87, $a2, $9d, $a8, $a7, $ff, $ff, $ff, $ff, $ff
.byte $92, $9a, $a6, $ae, $ab, $9a, $a2, $ff, $92, $c5
.byte $8b, $9e, $af, $9e, $a5, $ff, $b7, $b4, $ff, $8c
.byte $87, $a2, $9d, $a8, $a7, $a2, $ad, $9e, $ff, $ff
.byte $85, $a2, $9e, $a7, $9d, $ff, $ff, $ff, $ff, $ff
.byte $86, $a8, $9d, $9d, $9e, $ac, $ac, $ff, $ff, $ff
.byte $83, $9e, $a6, $a8, $a7, $ff, $ff, $ff, $ff, $ff
.byte $8a, $9e, $9f, $a4, $9a, $ff, $ff, $ff, $ff, $ff
.byte $8b, $9e, $af, $9e, $a5, $ff, $b8, $b4, $ff, $8c
.byte $94, $a5, $ad, $ab, $a8, $ac, $ff, $ff, $ff, $ff
.byte $94, $a5, $ad, $ab, $a8, $ac, $ff, $ff, $ff, $ff
.byte $94, $a5, $ad, $ab, $a8, $ac, $ff, $ff, $ff, $ff
.byte $93, $b2, $a9, $a1, $a8, $a7, $ff, $ff, $ff, $ff
.byte $8b, $9e, $af, $9e, $a5, $ff, $b6, $b4, $ff, $8c
.byte $92, $a2, $9e, $a0, $9f, $ab, $a2, $9e, $9d, $ff
.byte $8b, $9e, $af, $9e, $a5, $ff, $b5, $b4, $ff, $8c
.byte $8b, $9e, $af, $9e, $a5, $ff, $b9, $b4, $ff, $8c
.byte $87, $9e, $9a, $9d, $ff, $ff, $ff, $ff, $ff, $ff
.byte $98, $a6, $a2, $ab, $ff, $87, $9e, $9a, $9d, $ff
.byte $82, $a8, $a5, $a8, $ac, $ac, $ae, $ac, $ff, $ff
.byte $82, $b3, $9a, $ab, $ff, $83, $c5, $ff, $ff, $ff
.byte $8c, $9a, $ac, $ad, $9e, $ab, $ff, $93, $c5, $ff
.byte $8b, $9e, $af, $9e, $a5, $ff, $ba, $b4, $ff, $8c
.byte $8c, $9e, $ab, $9c, $a1, $9a, $a7, $ad, $ff, $ff
.byte $81, $a2, $ab, $ad, $a1, $9d, $9a, $b2, $ff, $92
.byte $93, $9e, $a7, $ad, $9a, $9c, $a5, $9e, $ff, $ff
.byte $93, $9e, $a7, $ad, $9a, $9c, $a5, $9e, $ff, $ff
.byte $93, $9e, $a7, $ad, $9a, $9c, $a5, $9e, $ff, $ff
.byte $91, $a2, $a0, $a1, $ad, $ff, $81, $c5, $ff, $ff
.byte $8b, $9e, $9f, $ad, $ff, $81, $c5, $ff, $ff, $ff
.byte $91, $9a, $a1, $ae, $ff, $ff, $ff, $ff, $ff, $ff
.byte $8a, $9e, $ad, $ae, $ff, $ff, $ff, $ff, $ff, $ff
.byte $8b, $9e, $af, $9e, $a5, $ff, $bb, $b4, $ff, $8c
.byte $95, $9a, $a5, $a2, $a0, $9a, $ab, $c5, $ff, $ff
.byte $8b, $9a, $ac, $9e, $ab, $ff, $86, $ae, $a7, $ff
.byte $81, $a2, $ad, $ff, $ff, $ff, $ff, $ff, $ff, $ff
.byte $8c, $a2, $ac, $ac, $a2, $a5, $9e, $ff, $81, $c5
.byte $82, $a1, $9a, $9d, $9a, $ab, $a7, $a8, $a8, $a4
.byte $88, $9c, $9e, $ff, $83, $c5, $ff, $ff, $ff, $ff
.byte $8a, $9e, $9f, $a4, $9a, $ff, $ff, $ff, $ff, $ff
.byte $92, $ad, $a8, $ab, $a6, $ff, $83, $c5, $ff, $ff
.byte $84, $9a, $ab, $ad, $a1, $ff, $83, $c5, $ff, $ff
.byte $88, $a9, $a8, $a8, $a1, $ff, $ff, $ff, $ff, $ff
.byte $8b, $9e, $9a, $9d, $9e, $ab, $ff, $ff, $ff, $ff
.byte $86, $ab, $ae, $a7, $ad, $ff, $ff, $ff, $ff, $ff
.byte $86, $a8, $a5, $9d, $ff, $83, $c5, $ff, $ff, $ff
.byte $92, $a4, $ae, $a5, $a5, $ff, $83, $c5, $ff, $ff
.byte $81, $a5, $ae, $9e, $ff, $83, $c5, $ff, $ff, $ff
.byte $91, $9e, $9d, $ff, $83, $ab, $9a, $a0, $a8, $a7
.byte $8e, $a9, $a2, $a7, $a2, $9c, $ae, $ac, $ff, $85
.byte $91, $a1, $a2, $b3, $a8, $a9, $9a, $ac, $ff, $ff
.byte $80, $a9, $a9, $9a, $ab, $a2, $ad, $a2, $a8, $a7
.byte $92, $a1, $a8, $ab, $ad, $ff, $80, $ab, $a6, $ff
.byte $8b, $a8, $a7, $a0, $ff, $80, $ab, $a6, $ff, $ff
.byte $85, $9a, $9c, $9e, $ff, $ff, $ff, $ff, $ff, $ff
.byte $93, $a2, $a0, $9e, $ab, $ff, $ff, $ff, $ff, $ff
.byte $93, $a8, $a8, $a5, $ac, $ff, $ff, $ff, $ff, $ff
.byte $8c, $9a, $a0, $a2, $9c, $ff, $ff, $ff, $ff, $ff
.byte $87, $a2, $ad, $ff, $ff, $ff, $ff, $ff, $ff, $ff
.byte $86, $a2, $ab, $a5, $ff, $ff, $ff, $ff, $ff, $ff
.byte $92, $a5, $9e, $9e, $a9, $ff, $ff, $ff, $ff, $ff
.byte $87, $a2, $9d, $a8, $a7, $a2, $ad, $9e, $ff, $ff
.byte $87, $a2, $9d, $a8, $a7, $a2, $ad, $9e, $ff, $ff
.byte $87, $a2, $9d, $a8, $a7, $a2, $ad, $9e, $ff, $ff
.byte $8b, $9e, $af, $9e, $a5, $ff, $bc, $b4, $ff, $8c
.byte $8b, $9e, $af, $9e, $a5, $ff, $bd, $b4, $ff, $8c
.byte $8f, $ab, $a8, $ad, $a8, $ff, $80, $c5, $ff, $ff
.byte $8c, $9a, $a0, $a2, $9c, $ff, $8c, $c5, $ff, $ff
.byte $92, $a8, $ae, $a5, $ff, $92, $9a, $af, $9e, $ab
.byte $94, $a5, $ad, $ab, $a8, $ac, $ff, $ff, $ff, $ff
.byte $8d, $9a, $ae, $9d, $9e, $ff, $ff, $ff, $ff, $ff
.byte $87, $ae, $a6, $9b, $9a, $9b, $9a, $ff, $ff, $ff
.byte $87, $ae, $a6, $9b, $9a, $9b, $9a, $ff, $ff, $ff
.byte $87, $ae, $a6, $9b, $9a, $9b, $9a, $ff, $ff, $ff
.byte $87, $ae, $a6, $9b, $9a, $9b, $9a, $ff, $ff, $ff
.byte $99, $a8, $a7, $9e, $ff, $84, $9a, $ad, $9e, $ab
.byte $8e, $9f, $9f, $a2, $9c, $9e, $ab, $ff, $ff, $ff
.byte $82, $9a, $9d, $9e, $ad, $ff, $ff, $ff, $ff, $ff
.byte $92, $a8, $a5, $9d, $a2, $9e, $ab, $ff, $ff, $ff
.byte $94, $a5, $ad, $a2, $a6, $9a, $ff, $ff, $ff, $ff

.segment "DATA"

ff6vwf_long_enemy_names:
    .word .loword(ff6vwf_long_enemy_name_000)
    .word .loword(ff6vwf_long_enemy_name_001)
    .word .loword(ff6vwf_long_enemy_name_002)
    .word .loword(ff6vwf_long_enemy_name_003)
    .word .loword(ff6vwf_long_enemy_name_004)
    .word .loword(ff6vwf_long_enemy_name_005)
    .word .loword(ff6vwf_long_enemy_name_006)
    .word .loword(ff6vwf_long_enemy_name_007)
    .word .loword(ff6vwf_long_enemy_name_008)
    .word .loword(ff6vwf_long_enemy_name_009)
    .word .loword(ff6vwf_long_enemy_name_010)
    .word .loword(ff6vwf_long_enemy_name_011)
    .word .loword(ff6vwf_long_enemy_name_012)
    .word .loword(ff6vwf_long_enemy_name_013)
    .word .loword(ff6vwf_long_enemy_name_014)
    .word .loword(ff6vwf_long_enemy_name_015)
    .word .loword(ff6vwf_long_enemy_name_016)
    .word .loword(ff6vwf_long_enemy_name_017)
    .word .loword(ff6vwf_long_enemy_name_018)
    .word .loword(ff6vwf_long_enemy_name_019)
    .word .loword(ff6vwf_long_enemy_name_020)
    .word .loword(ff6vwf_long_enemy_name_021)
    .word .loword(ff6vwf_long_enemy_name_022)
    .word .loword(ff6vwf_long_enemy_name_023)
    .word .loword(ff6vwf_long_enemy_name_024)
    .word .loword(ff6vwf_long_enemy_name_025)
    .word .loword(ff6vwf_long_enemy_name_026)
    .word .loword(ff6vwf_long_enemy_name_027)
    .word .loword(ff6vwf_long_enemy_name_028)
    .word .loword(ff6vwf_long_enemy_name_029)
    .word .loword(ff6vwf_long_enemy_name_030)
    .word .loword(ff6vwf_long_enemy_name_031)
    .word .loword(ff6vwf_long_enemy_name_032)
    .word .loword(ff6vwf_long_enemy_name_033)
    .word .loword(ff6vwf_long_enemy_name_034)
    .word .loword(ff6vwf_long_enemy_name_035)
    .word .loword(ff6vwf_long_enemy_name_036)
    .word .loword(ff6vwf_long_enemy_name_037)
    .word .loword(ff6vwf_long_enemy_name_038)
    .word .loword(ff6vwf_long_enemy_name_039)
    .word .loword(ff6vwf_long_enemy_name_040)
    .word .loword(ff6vwf_long_enemy_name_041)
    .word .loword(ff6vwf_long_enemy_name_042)
    .word .loword(ff6vwf_long_enemy_name_043)
    .word .loword(ff6vwf_long_enemy_name_044)
    .word .loword(ff6vwf_long_enemy_name_045)
    .word .loword(ff6vwf_long_enemy_name_046)
    .word .loword(ff6vwf_long_enemy_name_047)
    .word .loword(ff6vwf_long_enemy_name_048)
    .word .loword(ff6vwf_long_enemy_name_049)
    .word .loword(ff6vwf_long_enemy_name_050)
    .word .loword(ff6vwf_long_enemy_name_051)
    .word .loword(ff6vwf_long_enemy_name_052)
    .word .loword(ff6vwf_long_enemy_name_053)
    .word .loword(ff6vwf_long_enemy_name_054)
    .word .loword(ff6vwf_long_enemy_name_055)
    .word .loword(ff6vwf_long_enemy_name_056)
    .word .loword(ff6vwf_long_enemy_name_057)
    .word .loword(ff6vwf_long_enemy_name_058)
    .word .loword(ff6vwf_long_enemy_name_059)
    .word .loword(ff6vwf_long_enemy_name_060)
    .word .loword(ff6vwf_long_enemy_name_061)
    .word .loword(ff6vwf_long_enemy_name_062)
    .word .loword(ff6vwf_long_enemy_name_063)
    .word .loword(ff6vwf_long_enemy_name_064)
    .word .loword(ff6vwf_long_enemy_name_065)
    .word .loword(ff6vwf_long_enemy_name_066)
    .word .loword(ff6vwf_long_enemy_name_067)
    .word .loword(ff6vwf_long_enemy_name_068)
    .word .loword(ff6vwf_long_enemy_name_069)
    .word .loword(ff6vwf_long_enemy_name_070)
    .word .loword(ff6vwf_long_enemy_name_071)
    .word .loword(ff6vwf_long_enemy_name_072)
    .word .loword(ff6vwf_long_enemy_name_073)
    .word .loword(ff6vwf_long_enemy_name_074)
    .word .loword(ff6vwf_long_enemy_name_075)
    .word .loword(ff6vwf_long_enemy_name_076)
    .word .loword(ff6vwf_long_enemy_name_077)
    .word .loword(ff6vwf_long_enemy_name_078)
    .word .loword(ff6vwf_long_enemy_name_079)
    .word .loword(ff6vwf_long_enemy_name_080)
    .word .loword(ff6vwf_long_enemy_name_081)
    .word .loword(ff6vwf_long_enemy_name_082)
    .word .loword(ff6vwf_long_enemy_name_083)
    .word .loword(ff6vwf_long_enemy_name_084)
    .word .loword(ff6vwf_long_enemy_name_085)
    .word .loword(ff6vwf_long_enemy_name_086)
    .word .loword(ff6vwf_long_enemy_name_087)
    .word .loword(ff6vwf_long_enemy_name_088)
    .word .loword(ff6vwf_long_enemy_name_089)
    .word .loword(ff6vwf_long_enemy_name_090)
    .word .loword(ff6vwf_long_enemy_name_091)
    .word .loword(ff6vwf_long_enemy_name_092)
    .word .loword(ff6vwf_long_enemy_name_093)
    .word .loword(ff6vwf_long_enemy_name_094)
    .word .loword(ff6vwf_long_enemy_name_095)
    .word .loword(ff6vwf_long_enemy_name_096)
    .word .loword(ff6vwf_long_enemy_name_097)
    .word .loword(ff6vwf_long_enemy_name_098)
    .word .loword(ff6vwf_long_enemy_name_099)
    .word .loword(ff6vwf_long_enemy_name_100)
    .word .loword(ff6vwf_long_enemy_name_101)
    .word .loword(ff6vwf_long_enemy_name_102)
    .word .loword(ff6vwf_long_enemy_name_103)
    .word .loword(ff6vwf_long_enemy_name_104)
    .word .loword(ff6vwf_long_enemy_name_105)
    .word .loword(ff6vwf_long_enemy_name_106)
    .word .loword(ff6vwf_long_enemy_name_107)
    .word .loword(ff6vwf_long_enemy_name_108)
    .word .loword(ff6vwf_long_enemy_name_109)
    .word .loword(ff6vwf_long_enemy_name_110)
    .word .loword(ff6vwf_long_enemy_name_111)
    .word .loword(ff6vwf_long_enemy_name_112)
    .word .loword(ff6vwf_long_enemy_name_113)
    .word .loword(ff6vwf_long_enemy_name_114)
    .word .loword(ff6vwf_long_enemy_name_115)
    .word .loword(ff6vwf_long_enemy_name_116)
    .word .loword(ff6vwf_long_enemy_name_117)
    .word .loword(ff6vwf_long_enemy_name_118)
    .word .loword(ff6vwf_long_enemy_name_119)
    .word .loword(ff6vwf_long_enemy_name_120)
    .word .loword(ff6vwf_long_enemy_name_121)
    .word .loword(ff6vwf_long_enemy_name_122)
    .word .loword(ff6vwf_long_enemy_name_123)
    .word .loword(ff6vwf_long_enemy_name_124)
    .word .loword(ff6vwf_long_enemy_name_125)
    .word .loword(ff6vwf_long_enemy_name_126)
    .word .loword(ff6vwf_long_enemy_name_127)
    .word .loword(ff6vwf_long_enemy_name_128)
    .word .loword(ff6vwf_long_enemy_name_129)
    .word .loword(ff6vwf_long_enemy_name_130)
    .word .loword(ff6vwf_long_enemy_name_131)
    .word .loword(ff6vwf_long_enemy_name_132)
    .word .loword(ff6vwf_long_enemy_name_133)
    .word .loword(ff6vwf_long_enemy_name_134)
    .word .loword(ff6vwf_long_enemy_name_135)
    .word .loword(ff6vwf_long_enemy_name_136)
    .word .loword(ff6vwf_long_enemy_name_137)
    .word .loword(ff6vwf_long_enemy_name_138)
    .word .loword(ff6vwf_long_enemy_name_139)
    .word .loword(ff6vwf_long_enemy_name_140)
    .word .loword(ff6vwf_long_enemy_name_141)
    .word .loword(ff6vwf_long_enemy_name_142)
    .word .loword(ff6vwf_long_enemy_name_143)
    .word .loword(ff6vwf_long_enemy_name_144)
    .word .loword(ff6vwf_long_enemy_name_145)
    .word .loword(ff6vwf_long_enemy_name_146)
    .word .loword(ff6vwf_long_enemy_name_147)
    .word .loword(ff6vwf_long_enemy_name_148)
    .word .loword(ff6vwf_long_enemy_name_149)
    .word .loword(ff6vwf_long_enemy_name_150)
    .word .loword(ff6vwf_long_enemy_name_151)
    .word .loword(ff6vwf_long_enemy_name_152)
    .word .loword(ff6vwf_long_enemy_name_153)
    .word .loword(ff6vwf_long_enemy_name_154)
    .word .loword(ff6vwf_long_enemy_name_155)
    .word .loword(ff6vwf_long_enemy_name_156)
    .word .loword(ff6vwf_long_enemy_name_157)
    .word .loword(ff6vwf_long_enemy_name_158)
    .word .loword(ff6vwf_long_enemy_name_159)
    .word .loword(ff6vwf_long_enemy_name_160)
    .word .loword(ff6vwf_long_enemy_name_161)
    .word .loword(ff6vwf_long_enemy_name_162)
    .word .loword(ff6vwf_long_enemy_name_163)
    .word .loword(ff6vwf_long_enemy_name_164)
    .word .loword(ff6vwf_long_enemy_name_165)
    .word .loword(ff6vwf_long_enemy_name_166)
    .word .loword(ff6vwf_long_enemy_name_167)
    .word .loword(ff6vwf_long_enemy_name_168)
    .word .loword(ff6vwf_long_enemy_name_169)
    .word .loword(ff6vwf_long_enemy_name_170)
    .word .loword(ff6vwf_long_enemy_name_171)
    .word .loword(ff6vwf_long_enemy_name_172)
    .word .loword(ff6vwf_long_enemy_name_173)
    .word .loword(ff6vwf_long_enemy_name_174)
    .word .loword(ff6vwf_long_enemy_name_175)
    .word .loword(ff6vwf_long_enemy_name_176)
    .word .loword(ff6vwf_long_enemy_name_177)
    .word .loword(ff6vwf_long_enemy_name_178)
    .word .loword(ff6vwf_long_enemy_name_179)
    .word .loword(ff6vwf_long_enemy_name_180)
    .word .loword(ff6vwf_long_enemy_name_181)
    .word .loword(ff6vwf_long_enemy_name_182)
    .word .loword(ff6vwf_long_enemy_name_183)
    .word .loword(ff6vwf_long_enemy_name_184)
    .word .loword(ff6vwf_long_enemy_name_185)
    .word .loword(ff6vwf_long_enemy_name_186)
    .word .loword(ff6vwf_long_enemy_name_187)
    .word .loword(ff6vwf_long_enemy_name_188)
    .word .loword(ff6vwf_long_enemy_name_189)
    .word .loword(ff6vwf_long_enemy_name_190)
    .word .loword(ff6vwf_long_enemy_name_191)
    .word .loword(ff6vwf_long_enemy_name_192)
    .word .loword(ff6vwf_long_enemy_name_193)
    .word .loword(ff6vwf_long_enemy_name_194)
    .word .loword(ff6vwf_long_enemy_name_195)
    .word .loword(ff6vwf_long_enemy_name_196)
    .word .loword(ff6vwf_long_enemy_name_197)
    .word .loword(ff6vwf_long_enemy_name_198)
    .word .loword(ff6vwf_long_enemy_name_199)
    .word .loword(ff6vwf_long_enemy_name_200)
    .word .loword(ff6vwf_long_enemy_name_201)
    .word .loword(ff6vwf_long_enemy_name_202)
    .word .loword(ff6vwf_long_enemy_name_203)
    .word .loword(ff6vwf_long_enemy_name_204)
    .word .loword(ff6vwf_long_enemy_name_205)
    .word .loword(ff6vwf_long_enemy_name_206)
    .word .loword(ff6vwf_long_enemy_name_207)
    .word .loword(ff6vwf_long_enemy_name_208)
    .word .loword(ff6vwf_long_enemy_name_209)
    .word .loword(ff6vwf_long_enemy_name_210)
    .word .loword(ff6vwf_long_enemy_name_211)
    .word .loword(ff6vwf_long_enemy_name_212)
    .word .loword(ff6vwf_long_enemy_name_213)
    .word .loword(ff6vwf_long_enemy_name_214)
    .word .loword(ff6vwf_long_enemy_name_215)
    .word .loword(ff6vwf_long_enemy_name_216)
    .word .loword(ff6vwf_long_enemy_name_217)
    .word .loword(ff6vwf_long_enemy_name_218)
    .word .loword(ff6vwf_long_enemy_name_219)
    .word .loword(ff6vwf_long_enemy_name_220)
    .word .loword(ff6vwf_long_enemy_name_221)
    .word .loword(ff6vwf_long_enemy_name_222)
    .word .loword(ff6vwf_long_enemy_name_223)
    .word .loword(ff6vwf_long_enemy_name_224)
    .word .loword(ff6vwf_long_enemy_name_225)
    .word .loword(ff6vwf_long_enemy_name_226)
    .word .loword(ff6vwf_long_enemy_name_227)
    .word .loword(ff6vwf_long_enemy_name_228)
    .word .loword(ff6vwf_long_enemy_name_229)
    .word .loword(ff6vwf_long_enemy_name_230)
    .word .loword(ff6vwf_long_enemy_name_231)
    .word .loword(ff6vwf_long_enemy_name_232)
    .word .loword(ff6vwf_long_enemy_name_233)
    .word .loword(ff6vwf_long_enemy_name_234)
    .word .loword(ff6vwf_long_enemy_name_235)
    .word .loword(ff6vwf_long_enemy_name_236)
    .word .loword(ff6vwf_long_enemy_name_237)
    .word .loword(ff6vwf_long_enemy_name_238)
    .word .loword(ff6vwf_long_enemy_name_239)
    .word .loword(ff6vwf_long_enemy_name_240)
    .word .loword(ff6vwf_long_enemy_name_241)
    .word .loword(ff6vwf_long_enemy_name_242)
    .word .loword(ff6vwf_long_enemy_name_243)
    .word .loword(ff6vwf_long_enemy_name_244)
    .word .loword(ff6vwf_long_enemy_name_245)
    .word .loword(ff6vwf_long_enemy_name_246)
    .word .loword(ff6vwf_long_enemy_name_247)
    .word .loword(ff6vwf_long_enemy_name_248)
    .word .loword(ff6vwf_long_enemy_name_249)
    .word .loword(ff6vwf_long_enemy_name_250)
    .word .loword(ff6vwf_long_enemy_name_251)
    .word .loword(ff6vwf_long_enemy_name_252)
    .word .loword(ff6vwf_long_enemy_name_253)
    .word .loword(ff6vwf_long_enemy_name_254)
    .word .loword(ff6vwf_long_enemy_name_255)
    .word .loword(ff6vwf_long_enemy_name_256)
    .word .loword(ff6vwf_long_enemy_name_257)
    .word .loword(ff6vwf_long_enemy_name_258)
    .word .loword(ff6vwf_long_enemy_name_259)
    .word .loword(ff6vwf_long_enemy_name_260)
    .word .loword(ff6vwf_long_enemy_name_261)
    .word .loword(ff6vwf_long_enemy_name_262)
    .word .loword(ff6vwf_long_enemy_name_263)
    .word .loword(ff6vwf_long_enemy_name_264)
    .word .loword(ff6vwf_long_enemy_name_265)
    .word .loword(ff6vwf_long_enemy_name_266)
    .word .loword(ff6vwf_long_enemy_name_267)
    .word .loword(ff6vwf_long_enemy_name_268)
    .word .loword(ff6vwf_long_enemy_name_269)
    .word .loword(ff6vwf_long_enemy_name_270)
    .word .loword(ff6vwf_long_enemy_name_271)
    .word .loword(ff6vwf_long_enemy_name_272)
    .word .loword(ff6vwf_long_enemy_name_273)
    .word .loword(ff6vwf_long_enemy_name_274)
    .word .loword(ff6vwf_long_enemy_name_275)
    .word .loword(ff6vwf_long_enemy_name_276)
    .word .loword(ff6vwf_long_enemy_name_277)
    .word .loword(ff6vwf_long_enemy_name_278)
    .word .loword(ff6vwf_long_enemy_name_279)
    .word .loword(ff6vwf_long_enemy_name_280)
    .word .loword(ff6vwf_long_enemy_name_281)
    .word .loword(ff6vwf_long_enemy_name_282)
    .word .loword(ff6vwf_long_enemy_name_283)
    .word .loword(ff6vwf_long_enemy_name_284)
    .word .loword(ff6vwf_long_enemy_name_285)
    .word .loword(ff6vwf_long_enemy_name_286)
    .word .loword(ff6vwf_long_enemy_name_287)
    .word .loword(ff6vwf_long_enemy_name_288)
    .word .loword(ff6vwf_long_enemy_name_289)
    .word .loword(ff6vwf_long_enemy_name_290)
    .word .loword(ff6vwf_long_enemy_name_291)
    .word .loword(ff6vwf_long_enemy_name_292)
    .word .loword(ff6vwf_long_enemy_name_293)
    .word .loword(ff6vwf_long_enemy_name_294)
    .word .loword(ff6vwf_long_enemy_name_295)
    .word .loword(ff6vwf_long_enemy_name_296)
    .word .loword(ff6vwf_long_enemy_name_297)
    .word .loword(ff6vwf_long_enemy_name_298)
    .word .loword(ff6vwf_long_enemy_name_299)
    .word .loword(ff6vwf_long_enemy_name_300)
    .word .loword(ff6vwf_long_enemy_name_301)
    .word .loword(ff6vwf_long_enemy_name_302)
    .word .loword(ff6vwf_long_enemy_name_303)
    .word .loword(ff6vwf_long_enemy_name_304)
    .word .loword(ff6vwf_long_enemy_name_305)
    .word .loword(ff6vwf_long_enemy_name_306)
    .word .loword(ff6vwf_long_enemy_name_307)
    .word .loword(ff6vwf_long_enemy_name_308)
    .word .loword(ff6vwf_long_enemy_name_309)
    .word .loword(ff6vwf_long_enemy_name_310)
    .word .loword(ff6vwf_long_enemy_name_311)
    .word .loword(ff6vwf_long_enemy_name_312)
    .word .loword(ff6vwf_long_enemy_name_313)
    .word .loword(ff6vwf_long_enemy_name_314)
    .word .loword(ff6vwf_long_enemy_name_315)
    .word .loword(ff6vwf_long_enemy_name_316)
    .word .loword(ff6vwf_long_enemy_name_317)
    .word .loword(ff6vwf_long_enemy_name_318)
    .word .loword(ff6vwf_long_enemy_name_319)
    .word .loword(ff6vwf_long_enemy_name_320)
    .word .loword(ff6vwf_long_enemy_name_321)
    .word .loword(ff6vwf_long_enemy_name_322)
    .word .loword(ff6vwf_long_enemy_name_323)
    .word .loword(ff6vwf_long_enemy_name_324)
    .word .loword(ff6vwf_long_enemy_name_325)
    .word .loword(ff6vwf_long_enemy_name_326)
    .word .loword(ff6vwf_long_enemy_name_327)
    .word .loword(ff6vwf_long_enemy_name_328)
    .word .loword(ff6vwf_long_enemy_name_329)
    .word .loword(ff6vwf_long_enemy_name_330)
    .word .loword(ff6vwf_long_enemy_name_331)
    .word .loword(ff6vwf_long_enemy_name_332)
    .word .loword(ff6vwf_long_enemy_name_333)
    .word .loword(ff6vwf_long_enemy_name_334)
    .word .loword(ff6vwf_long_enemy_name_335)
    .word .loword(ff6vwf_long_enemy_name_336)
    .word .loword(ff6vwf_long_enemy_name_337)
    .word .loword(ff6vwf_long_enemy_name_338)
    .word .loword(ff6vwf_long_enemy_name_339)
    .word .loword(ff6vwf_long_enemy_name_340)
    .word .loword(ff6vwf_long_enemy_name_341)
    .word .loword(ff6vwf_long_enemy_name_342)
    .word .loword(ff6vwf_long_enemy_name_343)
    .word .loword(ff6vwf_long_enemy_name_344)
    .word .loword(ff6vwf_long_enemy_name_345)
    .word .loword(ff6vwf_long_enemy_name_346)
    .word .loword(ff6vwf_long_enemy_name_347)
    .word .loword(ff6vwf_long_enemy_name_348)
    .word .loword(ff6vwf_long_enemy_name_349)
    .word .loword(ff6vwf_long_enemy_name_350)
    .word .loword(ff6vwf_long_enemy_name_351)
    .word .loword(ff6vwf_long_enemy_name_352)
    .word .loword(ff6vwf_long_enemy_name_353)
    .word .loword(ff6vwf_long_enemy_name_354)
    .word .loword(ff6vwf_long_enemy_name_355)
    .word .loword(ff6vwf_long_enemy_name_356)
    .word .loword(ff6vwf_long_enemy_name_357)
    .word .loword(ff6vwf_long_enemy_name_358)
    .word .loword(ff6vwf_long_enemy_name_359)
    .word .loword(ff6vwf_long_enemy_name_360)
    .word .loword(ff6vwf_long_enemy_name_361)
    .word .loword(ff6vwf_long_enemy_name_362)
    .word .loword(ff6vwf_long_enemy_name_363)
    .word .loword(ff6vwf_long_enemy_name_364)
    .word .loword(ff6vwf_long_enemy_name_365)
    .word .loword(ff6vwf_long_enemy_name_366)
    .word .loword(ff6vwf_long_enemy_name_367)
    .word .loword(ff6vwf_long_enemy_name_368)
    .word .loword(ff6vwf_long_enemy_name_369)
    .word .loword(ff6vwf_long_enemy_name_370)
    .word .loword(ff6vwf_long_enemy_name_371)
    .word .loword(ff6vwf_long_enemy_name_372)
    .word .loword(ff6vwf_long_enemy_name_373)
    .word .loword(ff6vwf_long_enemy_name_374)
    .word .loword(ff6vwf_long_enemy_name_375)
    .word .loword(ff6vwf_long_enemy_name_376)
    .word .loword(ff6vwf_long_enemy_name_377)
    .word .loword(ff6vwf_long_enemy_name_378)
    .word .loword(ff6vwf_long_enemy_name_379)
    .word .loword(ff6vwf_long_enemy_name_380)
    .word .loword(ff6vwf_long_enemy_name_381)

ff6vwf_long_enemy_name_000: .asciiz "Guard"
ff6vwf_long_enemy_name_001: .asciiz "Imperial Soldier"
ff6vwf_long_enemy_name_002: .asciiz "Templar"
ff6vwf_long_enemy_name_003: .asciiz "Ninja"
ff6vwf_long_enemy_name_004: .asciiz "Samurai"
ff6vwf_long_enemy_name_005: .asciiz "Borghese"
ff6vwf_long_enemy_name_006: .asciiz "Magna Roader"
ff6vwf_long_enemy_name_007: .asciiz "Yojimbo"
ff6vwf_long_enemy_name_008: .asciiz "Cloud"
ff6vwf_long_enemy_name_009: .asciiz "Misty"
ff6vwf_long_enemy_name_010: .asciiz "Al Jabr"
ff6vwf_long_enemy_name_011: .asciiz "Zaghrem"
ff6vwf_long_enemy_name_012: .asciiz "Apocrypha"
ff6vwf_long_enemy_name_013: .asciiz "Dark Force"
ff6vwf_long_enemy_name_014: .asciiz "Angel Whisper"
ff6vwf_long_enemy_name_015: .asciiz "Oversoul"
ff6vwf_long_enemy_name_016: .asciiz "Skeletal Horror"
ff6vwf_long_enemy_name_017: .asciiz "Commander"
ff6vwf_long_enemy_name_018: .asciiz "Mu"
ff6vwf_long_enemy_name_019: .asciiz "Wererat"
ff6vwf_long_enemy_name_020: .asciiz "Mugbear"
ff6vwf_long_enemy_name_021: .asciiz "Belmodar"
ff6vwf_long_enemy_name_022: .asciiz "Muud Suud"
ff6vwf_long_enemy_name_023: .asciiz "Leaf Bunny"
ff6vwf_long_enemy_name_024: .asciiz "Stray Cat"
ff6vwf_long_enemy_name_025: .asciiz "Silver Lobo"
ff6vwf_long_enemy_name_026: .asciiz "Doberman"
ff6vwf_long_enemy_name_027: .asciiz "Megalodoth"
ff6vwf_long_enemy_name_028: .asciiz "Fidor"
ff6vwf_long_enemy_name_029: .asciiz "Briareus"
ff6vwf_long_enemy_name_030: .asciiz "Suriander"
ff6vwf_long_enemy_name_031: .asciiz "Chimera"
ff6vwf_long_enemy_name_032: .asciiz "Behemoth"
ff6vwf_long_enemy_name_033: .asciiz "Fafnir"
ff6vwf_long_enemy_name_034: .asciiz "Lesser Lopros"
ff6vwf_long_enemy_name_035: .asciiz "Fossil Dragon"
ff6vwf_long_enemy_name_036: .asciiz "Holy Dragon"
ff6vwf_long_enemy_name_037: .asciiz "Fiend Dragon"
ff6vwf_long_enemy_name_038: .asciiz "Brachiosaur"
ff6vwf_long_enemy_name_039: .asciiz "Tyrannosaur"
ff6vwf_long_enemy_name_040: .asciiz "Darkwind"
ff6vwf_long_enemy_name_041: .asciiz "Aepyornis"
ff6vwf_long_enemy_name_042: .asciiz "Vulture"
ff6vwf_long_enemy_name_043: .asciiz "Vasegiatta"
ff6vwf_long_enemy_name_044: .asciiz "Zokka"
ff6vwf_long_enemy_name_045: .asciiz "Trapper"
ff6vwf_long_enemy_name_046: .asciiz "Hornet"
ff6vwf_long_enemy_name_047: .asciiz "Nettlehopper"
ff6vwf_long_enemy_name_048: .asciiz "Delta Beetle"
ff6vwf_long_enemy_name_049: .asciiz "Killer Mantis"
ff6vwf_long_enemy_name_050: .asciiz "Trillium"
ff6vwf_long_enemy_name_051: .asciiz "Rafflesia"
ff6vwf_long_enemy_name_052: .asciiz "Tumbleweed"
ff6vwf_long_enemy_name_053: .asciiz "Vampire Thorn"
ff6vwf_long_enemy_name_054: .asciiz "Cartagra"
ff6vwf_long_enemy_name_055: .asciiz "Siegfried"
ff6vwf_long_enemy_name_056: .asciiz "Nautiloid"
ff6vwf_long_enemy_name_057: .asciiz "Exocite"
ff6vwf_long_enemy_name_058: .asciiz "Anguiform"
ff6vwf_long_enemy_name_059: .asciiz "Leap Frog"
ff6vwf_long_enemy_name_060: .asciiz "Lizard"
ff6vwf_long_enemy_name_061: .asciiz "Litwor Chicken"
ff6vwf_long_enemy_name_062: .asciiz "Slagworm"
ff6vwf_long_enemy_name_063: .asciiz "Hell's Rider"
ff6vwf_long_enemy_name_064: .asciiz "Typhon"
ff6vwf_long_enemy_name_065: .asciiz "Onion Knight"
ff6vwf_long_enemy_name_066: .asciiz "Magitek Armor"
ff6vwf_long_enemy_name_067: .asciiz "Sky Armor"
ff6vwf_long_enemy_name_068: .asciiz "Satellite"
ff6vwf_long_enemy_name_069: .asciiz "Armored Weapon"
ff6vwf_long_enemy_name_070: .asciiz "Spritzer"
ff6vwf_long_enemy_name_071: .asciiz "Flan"
ff6vwf_long_enemy_name_072: .asciiz "Outcast"
ff6vwf_long_enemy_name_073: .asciiz "Humpty"
ff6vwf_long_enemy_name_074: .asciiz "Brainpan"
ff6vwf_long_enemy_name_075: .asciiz "Cruller"
ff6vwf_long_enemy_name_076: .asciiz "Cactuar"
ff6vwf_long_enemy_name_077: .asciiz "Bandit"
ff6vwf_long_enemy_name_078: .asciiz "Harvester"
ff6vwf_long_enemy_name_079: .asciiz "Bomb"
ff6vwf_long_enemy_name_080: .asciiz "Still Life"
ff6vwf_long_enemy_name_081: .asciiz "Lunatys"
ff6vwf_long_enemy_name_082: .asciiz "Veil Dancer"
ff6vwf_long_enemy_name_083: .asciiz "Hill Gigas"
ff6vwf_long_enemy_name_084: .asciiz "Tonberry"
ff6vwf_long_enemy_name_085: .asciiz "Magic Urn"
ff6vwf_long_enemy_name_086: .asciiz "Mover"
ff6vwf_long_enemy_name_087: .asciiz "Figaro Lizard"
ff6vwf_long_enemy_name_088: .asciiz "Devoahan"
ff6vwf_long_enemy_name_089: .asciiz "Aspiran"
ff6vwf_long_enemy_name_090: .asciiz "Ghost"
ff6vwf_long_enemy_name_091: .asciiz "Crawler"
ff6vwf_long_enemy_name_092: .asciiz "Sand Ray"
ff6vwf_long_enemy_name_093: .asciiz "Alacran"
ff6vwf_long_enemy_name_094: .asciiz "Actinian"
ff6vwf_long_enemy_name_095: .asciiz "Sandhorse"
ff6vwf_long_enemy_name_096: .asciiz "Darkside"
ff6vwf_long_enemy_name_097: .asciiz "Malboro"
ff6vwf_long_enemy_name_098: .asciiz "Urok"
ff6vwf_long_enemy_name_099: .asciiz "Foper"
ff6vwf_long_enemy_name_100: .asciiz "Guard Leader"
ff6vwf_long_enemy_name_101: .asciiz "Corporal"
ff6vwf_long_enemy_name_102: .asciiz "General"
ff6vwf_long_enemy_name_103: .asciiz "Covert"
ff6vwf_long_enemy_name_104: .asciiz "Kamui"
ff6vwf_long_enemy_name_105: .asciiz "Warlock"
ff6vwf_long_enemy_name_106: .asciiz "Cherry"
ff6vwf_long_enemy_name_107: .asciiz "Joker"
ff6vwf_long_enemy_name_108: .asciiz "Iron Fist"
ff6vwf_long_enemy_name_109: .asciiz "Devil"
ff6vwf_long_enemy_name_110: .asciiz "Provoker"
ff6vwf_long_enemy_name_111: .asciiz "Cloudwraith"
ff6vwf_long_enemy_name_112: .asciiz "Mahadeva"
ff6vwf_long_enemy_name_113: .asciiz "Vector Hound"
ff6vwf_long_enemy_name_114: .asciiz "Peeper"
ff6vwf_long_enemy_name_115: .asciiz "Sewer Rat"
ff6vwf_long_enemy_name_116: .asciiz "Sorath"
ff6vwf_long_enemy_name_117: .asciiz "Destroyer"
ff6vwf_long_enemy_name_118: .asciiz "Chippirabbit"
ff6vwf_long_enemy_name_119: .asciiz "Coeurl Cat"
ff6vwf_long_enemy_name_120: .asciiz "Bloodfang"
ff6vwf_long_enemy_name_121: .asciiz "Hunting Hound"
ff6vwf_long_enemy_name_122: .asciiz "Gorgias"
ff6vwf_long_enemy_name_123: .asciiz "Don"
ff6vwf_long_enemy_name_124: .asciiz "Murussu"
ff6vwf_long_enemy_name_125: .asciiz "Wartpuck"
ff6vwf_long_enemy_name_126: .asciiz "Gorgimera"
ff6vwf_long_enemy_name_127: .asciiz "Behemoth King"
ff6vwf_long_enemy_name_128: .asciiz "Vector Lythos"
ff6vwf_long_enemy_name_129: .asciiz "Wyvern"
ff6vwf_long_enemy_name_130: .asciiz "Zombie Dragon"
ff6vwf_long_enemy_name_131: .asciiz "Dragon"
ff6vwf_long_enemy_name_132: .asciiz "Primeval Dragon"
ff6vwf_long_enemy_name_133: .asciiz "Weredragon"
ff6vwf_long_enemy_name_134: .asciiz "Cirpius"
ff6vwf_long_enemy_name_135: .asciiz "Sprinter"
ff6vwf_long_enemy_name_136: .asciiz "Lenergia"
ff6vwf_long_enemy_name_137: .asciiz "Marchosias"
ff6vwf_long_enemy_name_138: .asciiz "Gloomwind"
ff6vwf_long_enemy_name_139: .asciiz "Dropper"
ff6vwf_long_enemy_name_140: .asciiz "Rock Wasp"
ff6vwf_long_enemy_name_141: .asciiz "Grasswyrm"
ff6vwf_long_enemy_name_142: .asciiz "Luridan"
ff6vwf_long_enemy_name_143: .asciiz "Twinscythe"
ff6vwf_long_enemy_name_144: .asciiz "Paraladia"
ff6vwf_long_enemy_name_145: .asciiz "Exoray"
ff6vwf_long_enemy_name_146: .asciiz "Crusher"
ff6vwf_long_enemy_name_147: .asciiz "Ouroboros"
ff6vwf_long_enemy_name_148: .asciiz "Acrophies"
ff6vwf_long_enemy_name_149: .asciiz "Schmidt"
ff6vwf_long_enemy_name_150: .asciiz "Devourer"
ff6vwf_long_enemy_name_151: .asciiz "Cancer"
ff6vwf_long_enemy_name_152: .asciiz "Gigantoad"
ff6vwf_long_enemy_name_153: .asciiz "Basilisk"
ff6vwf_long_enemy_name_154: .asciiz "Medusa Chicken"
ff6vwf_long_enemy_name_155: .asciiz "Landworm"
ff6vwf_long_enemy_name_156: .asciiz "Test Rider"
ff6vwf_long_enemy_name_157: .asciiz "Pluto Armor"
ff6vwf_long_enemy_name_158: .asciiz "Onion Dasher"
ff6vwf_long_enemy_name_159: .asciiz "Heavy Armor"
ff6vwf_long_enemy_name_160: .asciiz "Chaser"
ff6vwf_long_enemy_name_161: .asciiz "Gamma"
ff6vwf_long_enemy_name_162: .asciiz "Poplium"
ff6vwf_long_enemy_name_163: .asciiz "Intangir"
ff6vwf_long_enemy_name_164: .asciiz "Misfit"
ff6vwf_long_enemy_name_165: .asciiz "Creature"
ff6vwf_long_enemy_name_166: .asciiz "Enuo"
ff6vwf_long_enemy_name_167: .asciiz "Deepeye"
ff6vwf_long_enemy_name_168: .asciiz "Unseelie"
ff6vwf_long_enemy_name_169: .asciiz "Neck Hunter"
ff6vwf_long_enemy_name_170: .asciiz "Grenade"
ff6vwf_long_enemy_name_171: .asciiz "Alluring Rider"
ff6vwf_long_enemy_name_172: .asciiz "Pandora"
ff6vwf_long_enemy_name_173: .asciiz "Blade Dancer"
ff6vwf_long_enemy_name_174: .asciiz "Gigantos"
ff6vwf_long_enemy_name_175: .asciiz "Magna Roader"
ff6vwf_long_enemy_name_176: .asciiz "Lycaon"
ff6vwf_long_enemy_name_177: .asciiz "Parasite"
ff6vwf_long_enemy_name_178: .asciiz "Land Ray"
ff6vwf_long_enemy_name_179: .asciiz "Antares"
ff6vwf_long_enemy_name_180: .asciiz "Anemone"
ff6vwf_long_enemy_name_181: .asciiz "Moonform"
ff6vwf_long_enemy_name_182: .asciiz "Spectre"
ff6vwf_long_enemy_name_183: .asciiz "Great Malboro"
ff6vwf_long_enemy_name_184: .asciiz "Bonnacon"
ff6vwf_long_enemy_name_185: .asciiz "Oceanus"
ff6vwf_long_enemy_name_186: .asciiz "Living Dead"
ff6vwf_long_enemy_name_187: .asciiz "Death Warden"
ff6vwf_long_enemy_name_188: .asciiz "Face"
ff6vwf_long_enemy_name_189: .asciiz "Outsider"
ff6vwf_long_enemy_name_190: .asciiz "Coco"
ff6vwf_long_enemy_name_191: .asciiz "Zeveak"
ff6vwf_long_enemy_name_192: .asciiz "Nightwalker"
ff6vwf_long_enemy_name_193: .asciiz "Demon Knight"
ff6vwf_long_enemy_name_194: .asciiz "Imperial Elite"
ff6vwf_long_enemy_name_195: .asciiz "Desert Hare"
ff6vwf_long_enemy_name_196: .asciiz "Wizard"
ff6vwf_long_enemy_name_197: .asciiz "Devil Fist"
ff6vwf_long_enemy_name_198: .asciiz "Illuyankas"
ff6vwf_long_enemy_name_199: .asciiz "Sergeant"
ff6vwf_long_enemy_name_200: .asciiz "Aspidochelon"
ff6vwf_long_enemy_name_201: .asciiz "Knotty"
ff6vwf_long_enemy_name_202: .asciiz "Luna Wolf"
ff6vwf_long_enemy_name_203: .asciiz "Belzecue"
ff6vwf_long_enemy_name_204: .asciiz "Caladrius"
ff6vwf_long_enemy_name_205: .asciiz "Tzakmaqiel"
ff6vwf_long_enemy_name_206: .asciiz "Lukhavi"
ff6vwf_long_enemy_name_207: .asciiz "Eukaryote"
ff6vwf_long_enemy_name_208: .asciiz "Land Grillon"
ff6vwf_long_enemy_name_209: .asciiz "Goetia"
ff6vwf_long_enemy_name_210: .asciiz "Greater Mantis"
ff6vwf_long_enemy_name_211: .asciiz "Bogy"
ff6vwf_long_enemy_name_212: .asciiz "Purusa"
ff6vwf_long_enemy_name_213: .asciiz "Black Dragon"
ff6vwf_long_enemy_name_214: .asciiz "Adamankary"
ff6vwf_long_enemy_name_215: .asciiz "Dante"
ff6vwf_long_enemy_name_216: .asciiz "Platinum Dragon"
ff6vwf_long_enemy_name_217: .asciiz "Duel Armor"
ff6vwf_long_enemy_name_218: .asciiz "Psychos"
ff6vwf_long_enemy_name_219: .asciiz "Mousse"
ff6vwf_long_enemy_name_220: .asciiz "Shambling Corpse"
ff6vwf_long_enemy_name_221: .asciiz "Punisher"
ff6vwf_long_enemy_name_222: .asciiz "Balloon"
ff6vwf_long_enemy_name_223: .asciiz "Gobbledygook"
ff6vwf_long_enemy_name_224: .asciiz "Great Behemoth"
ff6vwf_long_enemy_name_225: .asciiz "Scorpion"
ff6vwf_long_enemy_name_226: .asciiz "Chaos Dragon"
ff6vwf_long_enemy_name_227: .asciiz "Spitfire"
ff6vwf_long_enemy_name_228: .asciiz "Vector Chimera"
ff6vwf_long_enemy_name_229: .asciiz "Lich"
ff6vwf_long_enemy_name_230: .asciiz "Rukh"
ff6vwf_long_enemy_name_231: .asciiz "Magna Roader"
ff6vwf_long_enemy_name_232: .asciiz "Bug"
ff6vwf_long_enemy_name_233: .asciiz "Seaflower"
ff6vwf_long_enemy_name_234: .asciiz "Fortis"
ff6vwf_long_enemy_name_235: .asciiz "Venobennu"
ff6vwf_long_enemy_name_236: .asciiz "Galypdes"
ff6vwf_long_enemy_name_237: .asciiz "Junk"
ff6vwf_long_enemy_name_238: .asciiz "Mandrake"
ff6vwf_long_enemy_name_239: .asciiz "Valeor"
ff6vwf_long_enemy_name_240: .asciiz "Amduscias"
ff6vwf_long_enemy_name_241: .asciiz "Necromancer"
ff6vwf_long_enemy_name_242: .asciiz "Glasya Labolas"
ff6vwf_long_enemy_name_243: .asciiz "Magna Roader"
ff6vwf_long_enemy_name_244: .asciiz "Wild Rat"
ff6vwf_long_enemy_name_245: .asciiz "Gold Bear"
ff6vwf_long_enemy_name_246: .asciiz "InnoSent"
ff6vwf_long_enemy_name_247: .asciiz "Clymenus"
ff6vwf_long_enemy_name_248: .asciiz "Garm"
ff6vwf_long_enemy_name_249: .asciiz "Daedalus"
ff6vwf_long_enemy_name_250: .asciiz "Baalzephon"
ff6vwf_long_enemy_name_251: .asciiz "Ahriman"
ff6vwf_long_enemy_name_252: .asciiz "Death Machine"
ff6vwf_long_enemy_name_253: .asciiz "Metal Hitman"
ff6vwf_long_enemy_name_254: .asciiz "Io"
ff6vwf_long_enemy_name_255: .asciiz "Tonberries"
ff6vwf_long_enemy_name_256: .asciiz "Ymir"
ff6vwf_long_enemy_name_257: .asciiz "Angler Whelk"
ff6vwf_long_enemy_name_258: .asciiz "Mega Armor"
ff6vwf_long_enemy_name_259: .asciiz "Vargas"
ff6vwf_long_enemy_name_260: .asciiz "Tunnel Armor"
ff6vwf_long_enemy_name_261: .asciiz "Prometheus"
ff6vwf_long_enemy_name_262: .asciiz "Phantom Train"
ff6vwf_long_enemy_name_263: .asciiz "Dadaluma"
ff6vwf_long_enemy_name_264: .asciiz "Shiva"
ff6vwf_long_enemy_name_265: .asciiz "Ifrit"
ff6vwf_long_enemy_name_266: .asciiz "Number 024"
ff6vwf_long_enemy_name_267: .asciiz "Number 128"
ff6vwf_long_enemy_name_268: .asciiz "Inferno"
ff6vwf_long_enemy_name_269: .asciiz "Crane"
ff6vwf_long_enemy_name_270: .asciiz "Crane"
ff6vwf_long_enemy_name_271: .asciiz "Umaro"
ff6vwf_long_enemy_name_272: .asciiz "Umaro"
ff6vwf_long_enemy_name_273: .asciiz "Guardian"
ff6vwf_long_enemy_name_274: .asciiz "Guardian"
ff6vwf_long_enemy_name_275: .asciiz "Air Force"
ff6vwf_long_enemy_name_276: .asciiz "Valigarmanda"
ff6vwf_long_enemy_name_277: .asciiz "Valigarmanda"
ff6vwf_long_enemy_name_278: .asciiz "Flame Eater"
ff6vwf_long_enemy_name_279: .asciiz "Ultima Weapon"
ff6vwf_long_enemy_name_280: .asciiz "Nelapa"
ff6vwf_long_enemy_name_281: .asciiz "Behemoth King"
ff6vwf_long_enemy_name_282: .asciiz "Kefka"
ff6vwf_long_enemy_name_283: .asciiz "Tentacle"
ff6vwf_long_enemy_name_284: .asciiz "Dullahan"
ff6vwf_long_enemy_name_285: .asciiz "Deathgaze"
ff6vwf_long_enemy_name_286: .asciiz "Chadarnook"
ff6vwf_long_enemy_name_287: .asciiz "Curlax"
ff6vwf_long_enemy_name_288: .asciiz "Laragorn"
ff6vwf_long_enemy_name_289: .asciiz "Moebius"
ff6vwf_long_enemy_name_290: .asciiz "Wrexsoul"
ff6vwf_long_enemy_name_291: .asciiz "Hidon"
ff6vwf_long_enemy_name_292: .asciiz "Samurai Soul"
ff6vwf_long_enemy_name_293: .asciiz "Level 30 Magic"
ff6vwf_long_enemy_name_294: .asciiz "Hidonite"
ff6vwf_long_enemy_name_295: .asciiz "Fiend"
ff6vwf_long_enemy_name_296: .asciiz "Goddess"
ff6vwf_long_enemy_name_297: .asciiz "Demon"
ff6vwf_long_enemy_name_298: .asciiz "Kefka"
ff6vwf_long_enemy_name_299: .asciiz "Level 40 Magic"
ff6vwf_long_enemy_name_300: .asciiz "Ultros"
ff6vwf_long_enemy_name_301: .asciiz "Ultros"
ff6vwf_long_enemy_name_302: .asciiz "Ultros"
ff6vwf_long_enemy_name_303: .asciiz "Typhon"
ff6vwf_long_enemy_name_304: .asciiz "Level 20 Magic"
ff6vwf_long_enemy_name_305: .asciiz "Siegfried"
ff6vwf_long_enemy_name_306: .asciiz "Level 10 Magic"
ff6vwf_long_enemy_name_307: .asciiz "Level 50 Magic"
ff6vwf_long_enemy_name_308: .asciiz "Head"
ff6vwf_long_enemy_name_309: .asciiz "Ymir Head"
ff6vwf_long_enemy_name_310: .asciiz "Colossus"
ff6vwf_long_enemy_name_311: .asciiz "Czar Dragon"
ff6vwf_long_enemy_name_312: .asciiz "Master Tonberry"
ff6vwf_long_enemy_name_313: .asciiz "Level 60 Magic"
ff6vwf_long_enemy_name_314: .asciiz "Merchant"
ff6vwf_long_enemy_name_315: .asciiz "Birthday Suit"
ff6vwf_long_enemy_name_316: .asciiz "Tentacle"
ff6vwf_long_enemy_name_317: .asciiz "Tentacle"
ff6vwf_long_enemy_name_318: .asciiz "Tentacle"
ff6vwf_long_enemy_name_319: .asciiz "Right Blade"
ff6vwf_long_enemy_name_320: .asciiz "Left Blade"
ff6vwf_long_enemy_name_321: .asciiz "Rahu"
ff6vwf_long_enemy_name_322: .asciiz "Ketu"
ff6vwf_long_enemy_name_323: .asciiz "Level 70 Magic"
ff6vwf_long_enemy_name_324: .asciiz "Valigarmanda"
ff6vwf_long_enemy_name_325: .asciiz "Laser Gun"
ff6vwf_long_enemy_name_326: .asciiz "Bit"
ff6vwf_long_enemy_name_327: .asciiz "Missile Bay"
ff6vwf_long_enemy_name_328: .asciiz "Chadarnook"
ff6vwf_long_enemy_name_329: .asciiz "Ice Dragon"
ff6vwf_long_enemy_name_330: .asciiz "Kefka"
ff6vwf_long_enemy_name_331: .asciiz "Storm Dragon"
ff6vwf_long_enemy_name_332: .asciiz "Earth Dragon"
ff6vwf_long_enemy_name_333: .asciiz "Ipooh"
ff6vwf_long_enemy_name_334: .asciiz "Leader"
ff6vwf_long_enemy_name_335: .asciiz "Grunt"
ff6vwf_long_enemy_name_336: .asciiz "Gold Dragon"
ff6vwf_long_enemy_name_337: .asciiz "Skull Dragon"
ff6vwf_long_enemy_name_338: .asciiz "Blue Dragon"
ff6vwf_long_enemy_name_339: .asciiz "Red Dragon"
ff6vwf_long_enemy_name_340: .asciiz "Opinicus Fish"
ff6vwf_long_enemy_name_341: .asciiz "Rhizopas"
ff6vwf_long_enemy_name_342: .asciiz "Apparition"
ff6vwf_long_enemy_name_343: .asciiz "Short Arm"
ff6vwf_long_enemy_name_344: .asciiz "Long Arm"
ff6vwf_long_enemy_name_345: .asciiz "Face"
ff6vwf_long_enemy_name_346: .asciiz "Tiger"
ff6vwf_long_enemy_name_347: .asciiz "Tools"
ff6vwf_long_enemy_name_348: .asciiz "Magic"
ff6vwf_long_enemy_name_349: .asciiz "Hit"
ff6vwf_long_enemy_name_350: .asciiz "Girl"
ff6vwf_long_enemy_name_351: .asciiz "Sleep"
ff6vwf_long_enemy_name_352: .asciiz "Hidonite"
ff6vwf_long_enemy_name_353: .asciiz "Hidonite"
ff6vwf_long_enemy_name_354: .asciiz "Hidonite"
ff6vwf_long_enemy_name_355: .asciiz "Level 80 Magic"
ff6vwf_long_enemy_name_356: .asciiz "Level 90 Magic"
ff6vwf_long_enemy_name_357: .asciiz "Proto Armor"
ff6vwf_long_enemy_name_358: .asciiz "Magic Master"
ff6vwf_long_enemy_name_359: .asciiz "Soul Saver"
ff6vwf_long_enemy_name_360: .asciiz "Ultros"
ff6vwf_long_enemy_name_361: .asciiz "Naude"
ff6vwf_long_enemy_name_362: .asciiz "Humbaba"
ff6vwf_long_enemy_name_363: .asciiz "Humbaba"
ff6vwf_long_enemy_name_364: .asciiz "Humbaba"
ff6vwf_long_enemy_name_365: .asciiz "Humbaba"
ff6vwf_long_enemy_name_366: .asciiz ""
ff6vwf_long_enemy_name_367: .asciiz ""
ff6vwf_long_enemy_name_368: .asciiz ""
ff6vwf_long_enemy_name_369: .asciiz "Zone Eater"
ff6vwf_long_enemy_name_370: .asciiz ""
ff6vwf_long_enemy_name_371: .asciiz ""
ff6vwf_long_enemy_name_372: .asciiz ""
ff6vwf_long_enemy_name_373: .asciiz "Officer"
ff6vwf_long_enemy_name_374: .asciiz "Cadet"
ff6vwf_long_enemy_name_375: .asciiz ""
ff6vwf_long_enemy_name_376: .asciiz ""
ff6vwf_long_enemy_name_377: .asciiz "Soldier"
ff6vwf_long_enemy_name_378: .asciiz ""
ff6vwf_long_enemy_name_379: .asciiz ""
ff6vwf_long_enemy_name_380: .asciiz ""
ff6vwf_long_enemy_name_381: .asciiz "Ultima"

