ff6vwf_long_enemy_names:
    .word .loword(ff6vwf_long_enemy_name_000)
    .word .loword(ff6vwf_long_enemy_name_001)
    .word .loword(ff6vwf_long_enemy_name_002)
    .word .loword(ff6vwf_long_enemy_name_003)
    .word .loword(ff6vwf_long_enemy_name_004)
    .word .loword(ff6vwf_long_enemy_name_005)
    .word .loword(ff6vwf_long_enemy_name_006)
    .word .loword(ff6vwf_long_enemy_name_007)
    .word .loword(ff6vwf_long_enemy_name_008)
    .word .loword(ff6vwf_long_enemy_name_009)
    .word .loword(ff6vwf_long_enemy_name_010)
    .word .loword(ff6vwf_long_enemy_name_011)
    .word .loword(ff6vwf_long_enemy_name_012)
    .word .loword(ff6vwf_long_enemy_name_013)
    .word .loword(ff6vwf_long_enemy_name_014)
    .word .loword(ff6vwf_long_enemy_name_015)
    .word .loword(ff6vwf_long_enemy_name_016)
    .word .loword(ff6vwf_long_enemy_name_017)
    .word .loword(ff6vwf_long_enemy_name_018)
    .word .loword(ff6vwf_long_enemy_name_019)
    .word .loword(ff6vwf_long_enemy_name_020)
    .word .loword(ff6vwf_long_enemy_name_021)
    .word .loword(ff6vwf_long_enemy_name_022)
    .word .loword(ff6vwf_long_enemy_name_023)
    .word .loword(ff6vwf_long_enemy_name_024)
    .word .loword(ff6vwf_long_enemy_name_025)
    .word .loword(ff6vwf_long_enemy_name_026)
    .word .loword(ff6vwf_long_enemy_name_027)
    .word .loword(ff6vwf_long_enemy_name_028)
    .word .loword(ff6vwf_long_enemy_name_029)
    .word .loword(ff6vwf_long_enemy_name_030)
    .word .loword(ff6vwf_long_enemy_name_031)
    .word .loword(ff6vwf_long_enemy_name_032)
    .word .loword(ff6vwf_long_enemy_name_033)
    .word .loword(ff6vwf_long_enemy_name_034)
    .word .loword(ff6vwf_long_enemy_name_035)
    .word .loword(ff6vwf_long_enemy_name_036)
    .word .loword(ff6vwf_long_enemy_name_037)
    .word .loword(ff6vwf_long_enemy_name_038)
    .word .loword(ff6vwf_long_enemy_name_039)
    .word .loword(ff6vwf_long_enemy_name_040)
    .word .loword(ff6vwf_long_enemy_name_041)
    .word .loword(ff6vwf_long_enemy_name_042)
    .word .loword(ff6vwf_long_enemy_name_043)
    .word .loword(ff6vwf_long_enemy_name_044)
    .word .loword(ff6vwf_long_enemy_name_045)
    .word .loword(ff6vwf_long_enemy_name_046)
    .word .loword(ff6vwf_long_enemy_name_047)
    .word .loword(ff6vwf_long_enemy_name_048)
    .word .loword(ff6vwf_long_enemy_name_049)
    .word .loword(ff6vwf_long_enemy_name_050)
    .word .loword(ff6vwf_long_enemy_name_051)
    .word .loword(ff6vwf_long_enemy_name_052)
    .word .loword(ff6vwf_long_enemy_name_053)
    .word .loword(ff6vwf_long_enemy_name_054)
    .word .loword(ff6vwf_long_enemy_name_055)
    .word .loword(ff6vwf_long_enemy_name_056)
    .word .loword(ff6vwf_long_enemy_name_057)
    .word .loword(ff6vwf_long_enemy_name_058)
    .word .loword(ff6vwf_long_enemy_name_059)
    .word .loword(ff6vwf_long_enemy_name_060)
    .word .loword(ff6vwf_long_enemy_name_061)
    .word .loword(ff6vwf_long_enemy_name_062)
    .word .loword(ff6vwf_long_enemy_name_063)
    .word .loword(ff6vwf_long_enemy_name_064)
    .word .loword(ff6vwf_long_enemy_name_065)
    .word .loword(ff6vwf_long_enemy_name_066)
    .word .loword(ff6vwf_long_enemy_name_067)
    .word .loword(ff6vwf_long_enemy_name_068)
    .word .loword(ff6vwf_long_enemy_name_069)
    .word .loword(ff6vwf_long_enemy_name_070)
    .word .loword(ff6vwf_long_enemy_name_071)
    .word .loword(ff6vwf_long_enemy_name_072)
    .word .loword(ff6vwf_long_enemy_name_073)
    .word .loword(ff6vwf_long_enemy_name_074)
    .word .loword(ff6vwf_long_enemy_name_075)
    .word .loword(ff6vwf_long_enemy_name_076)
    .word .loword(ff6vwf_long_enemy_name_077)
    .word .loword(ff6vwf_long_enemy_name_078)
    .word .loword(ff6vwf_long_enemy_name_079)
    .word .loword(ff6vwf_long_enemy_name_080)
    .word .loword(ff6vwf_long_enemy_name_081)
    .word .loword(ff6vwf_long_enemy_name_082)
    .word .loword(ff6vwf_long_enemy_name_083)
    .word .loword(ff6vwf_long_enemy_name_084)
    .word .loword(ff6vwf_long_enemy_name_085)
    .word .loword(ff6vwf_long_enemy_name_086)
    .word .loword(ff6vwf_long_enemy_name_087)
    .word .loword(ff6vwf_long_enemy_name_088)
    .word .loword(ff6vwf_long_enemy_name_089)
    .word .loword(ff6vwf_long_enemy_name_090)
    .word .loword(ff6vwf_long_enemy_name_091)
    .word .loword(ff6vwf_long_enemy_name_092)
    .word .loword(ff6vwf_long_enemy_name_093)
    .word .loword(ff6vwf_long_enemy_name_094)
    .word .loword(ff6vwf_long_enemy_name_095)
    .word .loword(ff6vwf_long_enemy_name_096)
    .word .loword(ff6vwf_long_enemy_name_097)
    .word .loword(ff6vwf_long_enemy_name_098)
    .word .loword(ff6vwf_long_enemy_name_099)
    .word .loword(ff6vwf_long_enemy_name_100)
    .word .loword(ff6vwf_long_enemy_name_101)
    .word .loword(ff6vwf_long_enemy_name_102)
    .word .loword(ff6vwf_long_enemy_name_103)
    .word .loword(ff6vwf_long_enemy_name_104)
    .word .loword(ff6vwf_long_enemy_name_105)
    .word .loword(ff6vwf_long_enemy_name_106)
    .word .loword(ff6vwf_long_enemy_name_107)
    .word .loword(ff6vwf_long_enemy_name_108)
    .word .loword(ff6vwf_long_enemy_name_109)
    .word .loword(ff6vwf_long_enemy_name_110)
    .word .loword(ff6vwf_long_enemy_name_111)
    .word .loword(ff6vwf_long_enemy_name_112)
    .word .loword(ff6vwf_long_enemy_name_113)
    .word .loword(ff6vwf_long_enemy_name_114)
    .word .loword(ff6vwf_long_enemy_name_115)
    .word .loword(ff6vwf_long_enemy_name_116)
    .word .loword(ff6vwf_long_enemy_name_117)
    .word .loword(ff6vwf_long_enemy_name_118)
    .word .loword(ff6vwf_long_enemy_name_119)
    .word .loword(ff6vwf_long_enemy_name_120)
    .word .loword(ff6vwf_long_enemy_name_121)
    .word .loword(ff6vwf_long_enemy_name_122)
    .word .loword(ff6vwf_long_enemy_name_123)
    .word .loword(ff6vwf_long_enemy_name_124)
    .word .loword(ff6vwf_long_enemy_name_125)
    .word .loword(ff6vwf_long_enemy_name_126)
    .word .loword(ff6vwf_long_enemy_name_127)
    .word .loword(ff6vwf_long_enemy_name_128)
    .word .loword(ff6vwf_long_enemy_name_129)
    .word .loword(ff6vwf_long_enemy_name_130)
    .word .loword(ff6vwf_long_enemy_name_131)
    .word .loword(ff6vwf_long_enemy_name_132)
    .word .loword(ff6vwf_long_enemy_name_133)
    .word .loword(ff6vwf_long_enemy_name_134)
    .word .loword(ff6vwf_long_enemy_name_135)
    .word .loword(ff6vwf_long_enemy_name_136)
    .word .loword(ff6vwf_long_enemy_name_137)
    .word .loword(ff6vwf_long_enemy_name_138)
    .word .loword(ff6vwf_long_enemy_name_139)
    .word .loword(ff6vwf_long_enemy_name_140)
    .word .loword(ff6vwf_long_enemy_name_141)
    .word .loword(ff6vwf_long_enemy_name_142)
    .word .loword(ff6vwf_long_enemy_name_143)
    .word .loword(ff6vwf_long_enemy_name_144)
    .word .loword(ff6vwf_long_enemy_name_145)
    .word .loword(ff6vwf_long_enemy_name_146)
    .word .loword(ff6vwf_long_enemy_name_147)
    .word .loword(ff6vwf_long_enemy_name_148)
    .word .loword(ff6vwf_long_enemy_name_149)
    .word .loword(ff6vwf_long_enemy_name_150)
    .word .loword(ff6vwf_long_enemy_name_151)
    .word .loword(ff6vwf_long_enemy_name_152)
    .word .loword(ff6vwf_long_enemy_name_153)
    .word .loword(ff6vwf_long_enemy_name_154)
    .word .loword(ff6vwf_long_enemy_name_155)
    .word .loword(ff6vwf_long_enemy_name_156)
    .word .loword(ff6vwf_long_enemy_name_157)
    .word .loword(ff6vwf_long_enemy_name_158)
    .word .loword(ff6vwf_long_enemy_name_159)
    .word .loword(ff6vwf_long_enemy_name_160)
    .word .loword(ff6vwf_long_enemy_name_161)
    .word .loword(ff6vwf_long_enemy_name_162)
    .word .loword(ff6vwf_long_enemy_name_163)
    .word .loword(ff6vwf_long_enemy_name_164)
    .word .loword(ff6vwf_long_enemy_name_165)
    .word .loword(ff6vwf_long_enemy_name_166)
    .word .loword(ff6vwf_long_enemy_name_167)
    .word .loword(ff6vwf_long_enemy_name_168)
    .word .loword(ff6vwf_long_enemy_name_169)
    .word .loword(ff6vwf_long_enemy_name_170)
    .word .loword(ff6vwf_long_enemy_name_171)
    .word .loword(ff6vwf_long_enemy_name_172)
    .word .loword(ff6vwf_long_enemy_name_173)
    .word .loword(ff6vwf_long_enemy_name_174)
    .word .loword(ff6vwf_long_enemy_name_175)
    .word .loword(ff6vwf_long_enemy_name_176)
    .word .loword(ff6vwf_long_enemy_name_177)
    .word .loword(ff6vwf_long_enemy_name_178)
    .word .loword(ff6vwf_long_enemy_name_179)
    .word .loword(ff6vwf_long_enemy_name_180)
    .word .loword(ff6vwf_long_enemy_name_181)
    .word .loword(ff6vwf_long_enemy_name_182)
    .word .loword(ff6vwf_long_enemy_name_183)
    .word .loword(ff6vwf_long_enemy_name_184)
    .word .loword(ff6vwf_long_enemy_name_185)
    .word .loword(ff6vwf_long_enemy_name_186)
    .word .loword(ff6vwf_long_enemy_name_187)
    .word .loword(ff6vwf_long_enemy_name_188)
    .word .loword(ff6vwf_long_enemy_name_189)
    .word .loword(ff6vwf_long_enemy_name_190)
    .word .loword(ff6vwf_long_enemy_name_191)
    .word .loword(ff6vwf_long_enemy_name_192)
    .word .loword(ff6vwf_long_enemy_name_193)
    .word .loword(ff6vwf_long_enemy_name_194)
    .word .loword(ff6vwf_long_enemy_name_195)
    .word .loword(ff6vwf_long_enemy_name_196)
    .word .loword(ff6vwf_long_enemy_name_197)
    .word .loword(ff6vwf_long_enemy_name_198)
    .word .loword(ff6vwf_long_enemy_name_199)
    .word .loword(ff6vwf_long_enemy_name_200)
    .word .loword(ff6vwf_long_enemy_name_201)
    .word .loword(ff6vwf_long_enemy_name_202)
    .word .loword(ff6vwf_long_enemy_name_203)
    .word .loword(ff6vwf_long_enemy_name_204)
    .word .loword(ff6vwf_long_enemy_name_205)
    .word .loword(ff6vwf_long_enemy_name_206)
    .word .loword(ff6vwf_long_enemy_name_207)
    .word .loword(ff6vwf_long_enemy_name_208)
    .word .loword(ff6vwf_long_enemy_name_209)
    .word .loword(ff6vwf_long_enemy_name_210)
    .word .loword(ff6vwf_long_enemy_name_211)
    .word .loword(ff6vwf_long_enemy_name_212)
    .word .loword(ff6vwf_long_enemy_name_213)
    .word .loword(ff6vwf_long_enemy_name_214)
    .word .loword(ff6vwf_long_enemy_name_215)
    .word .loword(ff6vwf_long_enemy_name_216)
    .word .loword(ff6vwf_long_enemy_name_217)
    .word .loword(ff6vwf_long_enemy_name_218)
    .word .loword(ff6vwf_long_enemy_name_219)
    .word .loword(ff6vwf_long_enemy_name_220)
    .word .loword(ff6vwf_long_enemy_name_221)
    .word .loword(ff6vwf_long_enemy_name_222)
    .word .loword(ff6vwf_long_enemy_name_223)
    .word .loword(ff6vwf_long_enemy_name_224)
    .word .loword(ff6vwf_long_enemy_name_225)
    .word .loword(ff6vwf_long_enemy_name_226)
    .word .loword(ff6vwf_long_enemy_name_227)
    .word .loword(ff6vwf_long_enemy_name_228)
    .word .loword(ff6vwf_long_enemy_name_229)
    .word .loword(ff6vwf_long_enemy_name_230)
    .word .loword(ff6vwf_long_enemy_name_231)
    .word .loword(ff6vwf_long_enemy_name_232)
    .word .loword(ff6vwf_long_enemy_name_233)
    .word .loword(ff6vwf_long_enemy_name_234)
    .word .loword(ff6vwf_long_enemy_name_235)
    .word .loword(ff6vwf_long_enemy_name_236)
    .word .loword(ff6vwf_long_enemy_name_237)
    .word .loword(ff6vwf_long_enemy_name_238)
    .word .loword(ff6vwf_long_enemy_name_239)
    .word .loword(ff6vwf_long_enemy_name_240)
    .word .loword(ff6vwf_long_enemy_name_241)
    .word .loword(ff6vwf_long_enemy_name_242)
    .word .loword(ff6vwf_long_enemy_name_243)
    .word .loword(ff6vwf_long_enemy_name_244)
    .word .loword(ff6vwf_long_enemy_name_245)
    .word .loword(ff6vwf_long_enemy_name_246)
    .word .loword(ff6vwf_long_enemy_name_247)
    .word .loword(ff6vwf_long_enemy_name_248)
    .word .loword(ff6vwf_long_enemy_name_249)
    .word .loword(ff6vwf_long_enemy_name_250)
    .word .loword(ff6vwf_long_enemy_name_251)
    .word .loword(ff6vwf_long_enemy_name_252)
    .word .loword(ff6vwf_long_enemy_name_253)
    .word .loword(ff6vwf_long_enemy_name_254)
    .word .loword(ff6vwf_long_enemy_name_255)
    .word .loword(ff6vwf_long_enemy_name_256)
    .word .loword(ff6vwf_long_enemy_name_257)
    .word .loword(ff6vwf_long_enemy_name_258)
    .word .loword(ff6vwf_long_enemy_name_259)
    .word .loword(ff6vwf_long_enemy_name_260)
    .word .loword(ff6vwf_long_enemy_name_261)
    .word .loword(ff6vwf_long_enemy_name_262)
    .word .loword(ff6vwf_long_enemy_name_263)
    .word .loword(ff6vwf_long_enemy_name_264)
    .word .loword(ff6vwf_long_enemy_name_265)
    .word .loword(ff6vwf_long_enemy_name_266)
    .word .loword(ff6vwf_long_enemy_name_267)
    .word .loword(ff6vwf_long_enemy_name_268)
    .word .loword(ff6vwf_long_enemy_name_269)
    .word .loword(ff6vwf_long_enemy_name_270)
    .word .loword(ff6vwf_long_enemy_name_271)
    .word .loword(ff6vwf_long_enemy_name_272)
    .word .loword(ff6vwf_long_enemy_name_273)
    .word .loword(ff6vwf_long_enemy_name_274)
    .word .loword(ff6vwf_long_enemy_name_275)
    .word .loword(ff6vwf_long_enemy_name_276)
    .word .loword(ff6vwf_long_enemy_name_277)
    .word .loword(ff6vwf_long_enemy_name_278)
    .word .loword(ff6vwf_long_enemy_name_279)
    .word .loword(ff6vwf_long_enemy_name_280)
    .word .loword(ff6vwf_long_enemy_name_281)
    .word .loword(ff6vwf_long_enemy_name_282)
    .word .loword(ff6vwf_long_enemy_name_283)
    .word .loword(ff6vwf_long_enemy_name_284)
    .word .loword(ff6vwf_long_enemy_name_285)
    .word .loword(ff6vwf_long_enemy_name_286)
    .word .loword(ff6vwf_long_enemy_name_287)
    .word .loword(ff6vwf_long_enemy_name_288)
    .word .loword(ff6vwf_long_enemy_name_289)
    .word .loword(ff6vwf_long_enemy_name_290)
    .word .loword(ff6vwf_long_enemy_name_291)
    .word .loword(ff6vwf_long_enemy_name_292)
    .word .loword(ff6vwf_long_enemy_name_293)
    .word .loword(ff6vwf_long_enemy_name_294)
    .word .loword(ff6vwf_long_enemy_name_295)
    .word .loword(ff6vwf_long_enemy_name_296)
    .word .loword(ff6vwf_long_enemy_name_297)
    .word .loword(ff6vwf_long_enemy_name_298)
    .word .loword(ff6vwf_long_enemy_name_299)
    .word .loword(ff6vwf_long_enemy_name_300)
    .word .loword(ff6vwf_long_enemy_name_301)
    .word .loword(ff6vwf_long_enemy_name_302)
    .word .loword(ff6vwf_long_enemy_name_303)
    .word .loword(ff6vwf_long_enemy_name_304)
    .word .loword(ff6vwf_long_enemy_name_305)
    .word .loword(ff6vwf_long_enemy_name_306)
    .word .loword(ff6vwf_long_enemy_name_307)
    .word .loword(ff6vwf_long_enemy_name_308)
    .word .loword(ff6vwf_long_enemy_name_309)
    .word .loword(ff6vwf_long_enemy_name_310)
    .word .loword(ff6vwf_long_enemy_name_311)
    .word .loword(ff6vwf_long_enemy_name_312)
    .word .loword(ff6vwf_long_enemy_name_313)
    .word .loword(ff6vwf_long_enemy_name_314)
    .word .loword(ff6vwf_long_enemy_name_315)
    .word .loword(ff6vwf_long_enemy_name_316)
    .word .loword(ff6vwf_long_enemy_name_317)
    .word .loword(ff6vwf_long_enemy_name_318)
    .word .loword(ff6vwf_long_enemy_name_319)
    .word .loword(ff6vwf_long_enemy_name_320)
    .word .loword(ff6vwf_long_enemy_name_321)
    .word .loword(ff6vwf_long_enemy_name_322)
    .word .loword(ff6vwf_long_enemy_name_323)
    .word .loword(ff6vwf_long_enemy_name_324)
    .word .loword(ff6vwf_long_enemy_name_325)
    .word .loword(ff6vwf_long_enemy_name_326)
    .word .loword(ff6vwf_long_enemy_name_327)
    .word .loword(ff6vwf_long_enemy_name_328)
    .word .loword(ff6vwf_long_enemy_name_329)
    .word .loword(ff6vwf_long_enemy_name_330)
    .word .loword(ff6vwf_long_enemy_name_331)
    .word .loword(ff6vwf_long_enemy_name_332)
    .word .loword(ff6vwf_long_enemy_name_333)
    .word .loword(ff6vwf_long_enemy_name_334)
    .word .loword(ff6vwf_long_enemy_name_335)
    .word .loword(ff6vwf_long_enemy_name_336)
    .word .loword(ff6vwf_long_enemy_name_337)
    .word .loword(ff6vwf_long_enemy_name_338)
    .word .loword(ff6vwf_long_enemy_name_339)
    .word .loword(ff6vwf_long_enemy_name_340)
    .word .loword(ff6vwf_long_enemy_name_341)
    .word .loword(ff6vwf_long_enemy_name_342)
    .word .loword(ff6vwf_long_enemy_name_343)
    .word .loword(ff6vwf_long_enemy_name_344)
    .word .loword(ff6vwf_long_enemy_name_345)
    .word .loword(ff6vwf_long_enemy_name_346)
    .word .loword(ff6vwf_long_enemy_name_347)
    .word .loword(ff6vwf_long_enemy_name_348)
    .word .loword(ff6vwf_long_enemy_name_349)
    .word .loword(ff6vwf_long_enemy_name_350)
    .word .loword(ff6vwf_long_enemy_name_351)
    .word .loword(ff6vwf_long_enemy_name_352)
    .word .loword(ff6vwf_long_enemy_name_353)
    .word .loword(ff6vwf_long_enemy_name_354)
    .word .loword(ff6vwf_long_enemy_name_355)
    .word .loword(ff6vwf_long_enemy_name_356)
    .word .loword(ff6vwf_long_enemy_name_357)
    .word .loword(ff6vwf_long_enemy_name_358)
    .word .loword(ff6vwf_long_enemy_name_359)
    .word .loword(ff6vwf_long_enemy_name_360)
    .word .loword(ff6vwf_long_enemy_name_361)
    .word .loword(ff6vwf_long_enemy_name_362)
    .word .loword(ff6vwf_long_enemy_name_363)
    .word .loword(ff6vwf_long_enemy_name_364)
    .word .loword(ff6vwf_long_enemy_name_365)
    .word .loword(ff6vwf_long_enemy_name_366)
    .word .loword(ff6vwf_long_enemy_name_367)
    .word .loword(ff6vwf_long_enemy_name_368)
    .word .loword(ff6vwf_long_enemy_name_369)
    .word .loword(ff6vwf_long_enemy_name_370)
    .word .loword(ff6vwf_long_enemy_name_371)
    .word .loword(ff6vwf_long_enemy_name_372)
    .word .loword(ff6vwf_long_enemy_name_373)
    .word .loword(ff6vwf_long_enemy_name_374)
    .word .loword(ff6vwf_long_enemy_name_375)
    .word .loword(ff6vwf_long_enemy_name_376)
    .word .loword(ff6vwf_long_enemy_name_377)
    .word .loword(ff6vwf_long_enemy_name_378)
    .word .loword(ff6vwf_long_enemy_name_379)
    .word .loword(ff6vwf_long_enemy_name_380)
    .word .loword(ff6vwf_long_enemy_name_381)
    .word .loword(ff6vwf_long_enemy_name_382)
    .word .loword(ff6vwf_long_enemy_name_383)
    .word .loword(ff6vwf_long_enemy_name_384)
    .word .loword(ff6vwf_long_enemy_name_385)
    .word .loword(ff6vwf_long_enemy_name_386)
    .word .loword(ff6vwf_long_enemy_name_387)
    .word .loword(ff6vwf_long_enemy_name_388)
    .word .loword(ff6vwf_long_enemy_name_389)
    .word .loword(ff6vwf_long_enemy_name_390)
    .word .loword(ff6vwf_long_enemy_name_391)
    .word .loword(ff6vwf_long_enemy_name_392)
    .word .loword(ff6vwf_long_enemy_name_393)
    .word .loword(ff6vwf_long_enemy_name_394)
    .word .loword(ff6vwf_long_enemy_name_395)
    .word .loword(ff6vwf_long_enemy_name_396)
    .word .loword(ff6vwf_long_enemy_name_397)
    .word .loword(ff6vwf_long_enemy_name_398)
    .word .loword(ff6vwf_long_enemy_name_399)
    .word .loword(ff6vwf_long_enemy_name_400)
    .word .loword(ff6vwf_long_enemy_name_401)
    .word .loword(ff6vwf_long_enemy_name_402)
    .word .loword(ff6vwf_long_enemy_name_403)
    .word .loword(ff6vwf_long_enemy_name_404)
    .word .loword(ff6vwf_long_enemy_name_405)
    .word .loword(ff6vwf_long_enemy_name_406)
    .word .loword(ff6vwf_long_enemy_name_407)
    .word .loword(ff6vwf_long_enemy_name_408)
    .word .loword(ff6vwf_long_enemy_name_409)
    .word .loword(ff6vwf_long_enemy_name_410)
    .word .loword(ff6vwf_long_enemy_name_411)
    .word .loword(ff6vwf_long_enemy_name_412)
    .word .loword(ff6vwf_long_enemy_name_413)
    .word .loword(ff6vwf_long_enemy_name_414)
    .word .loword(ff6vwf_long_enemy_name_415)
    .word .loword(ff6vwf_long_enemy_name_416)
    .word .loword(ff6vwf_long_enemy_name_417)
    .word .loword(ff6vwf_long_enemy_name_418)
    .word .loword(ff6vwf_long_enemy_name_419)
    .word .loword(ff6vwf_long_enemy_name_420)
    .word .loword(ff6vwf_long_enemy_name_421)

ff6vwf_long_enemy_name_000: .asciiz "Guard" ; Guard
ff6vwf_long_enemy_name_001: .asciiz "Imperial Soldier" ; Soldier
ff6vwf_long_enemy_name_002: .asciiz "Templar" ; Templar
ff6vwf_long_enemy_name_003: .asciiz "Ninja" ; Ninja
ff6vwf_long_enemy_name_004: .asciiz "Samurai" ; Samurai
ff6vwf_long_enemy_name_005: .asciiz "Borghese" ; Orog
ff6vwf_long_enemy_name_006: .asciiz "Magna Roader" ; Mag Roader
ff6vwf_long_enemy_name_007: .asciiz "Yojimbo" ; Retainer
ff6vwf_long_enemy_name_008: .asciiz "Cloud" ; Hazer
ff6vwf_long_enemy_name_009: .asciiz "Misty" ; Dahling
ff6vwf_long_enemy_name_010: .asciiz "Al Jabr" ; Rain Man
ff6vwf_long_enemy_name_011: .asciiz "Zaghrem" ; Brawler
ff6vwf_long_enemy_name_012: .asciiz "Apocrypha" ; Apokryphos
ff6vwf_long_enemy_name_013: .asciiz "Dark Force" ; Dark Force
ff6vwf_long_enemy_name_014: .asciiz "Angel Whisper" ; Whisper
ff6vwf_long_enemy_name_015: .asciiz "Oversoul" ; Over-Mind
ff6vwf_long_enemy_name_016: .asciiz "Skeletal Horror" ; Osteosaur
ff6vwf_long_enemy_name_017: .asciiz "Commander" ; Commander
ff6vwf_long_enemy_name_018: .asciiz "Mu" ; Rhodox
ff6vwf_long_enemy_name_019: .asciiz "Wererat" ; Were-Rat
ff6vwf_long_enemy_name_020: .asciiz "Mugbear" ; Ursus
ff6vwf_long_enemy_name_021: .asciiz "Belmodar" ; Rhinotaur
ff6vwf_long_enemy_name_022: .asciiz "Muud Suud" ; Steroidite
ff6vwf_long_enemy_name_023: .asciiz "Leaf Bunny" ; Leafer
ff6vwf_long_enemy_name_024: .asciiz "Stray Cat" ; Stray Cat
ff6vwf_long_enemy_name_025: .asciiz "Silver Lobo" ; Lobo
ff6vwf_long_enemy_name_026: .asciiz "Doberman" ; Doberman
ff6vwf_long_enemy_name_027: .asciiz "Megalodoth" ; Vomammoth
ff6vwf_long_enemy_name_028: .asciiz "Fidor" ; Fidor
ff6vwf_long_enemy_name_029: .asciiz "Briareus" ; Baskervor
ff6vwf_long_enemy_name_030: .asciiz "Suriander" ; Suriander
ff6vwf_long_enemy_name_031: .asciiz "Chimera" ; Chimera
ff6vwf_long_enemy_name_032: .asciiz "Behemoth" ; Behemoth
ff6vwf_long_enemy_name_033: .asciiz "Fafnir" ; Mesosaur
ff6vwf_long_enemy_name_034: .asciiz "Lesser Lopros" ; Pterodon
ff6vwf_long_enemy_name_035: .asciiz "Fossil Dragon" ; FossilFang
ff6vwf_long_enemy_name_036: .asciiz "Holy Dragon" ; White Drgn
ff6vwf_long_enemy_name_037: .asciiz "Fiend Dragon" ; Doom Drgn
ff6vwf_long_enemy_name_038: .asciiz "Brachiosaur" ; Brachosaur
ff6vwf_long_enemy_name_039: .asciiz "Tyrannosaur" ; Tyranosaur
ff6vwf_long_enemy_name_040: .asciiz "Darkwind" ; Dark Wind
ff6vwf_long_enemy_name_041: .asciiz "Aepyornis" ; Beakor
ff6vwf_long_enemy_name_042: .asciiz "Vulture" ; Vulture
ff6vwf_long_enemy_name_043: .asciiz "Vasegiatta" ; Harpy
ff6vwf_long_enemy_name_044: .asciiz "Zokka" ; HermitCrab
ff6vwf_long_enemy_name_045: .asciiz "Trapper" ; Trapper
ff6vwf_long_enemy_name_046: .asciiz "Hornet" ; Hornet
ff6vwf_long_enemy_name_047: .asciiz "Nettlehopper" ; CrassHoppr
ff6vwf_long_enemy_name_048: .asciiz "Delta Beetle" ; Delta Bug
ff6vwf_long_enemy_name_049: .asciiz "Killer Mantis" ; Gilomantis
ff6vwf_long_enemy_name_050: .asciiz "Trillium" ; Trilium
ff6vwf_long_enemy_name_051: .asciiz "Rafflesia" ; Nightshade
ff6vwf_long_enemy_name_052: .asciiz "Tumbleweed" ; TumbleWeed
ff6vwf_long_enemy_name_053: .asciiz "Vampire Thorn" ; Bloompire
ff6vwf_long_enemy_name_054: .asciiz "Cartagra" ; Trilobiter
ff6vwf_long_enemy_name_055: .asciiz "Siegfried" ; Siegfried
ff6vwf_long_enemy_name_056: .asciiz "Nautiloid" ; Nautiloid
ff6vwf_long_enemy_name_057: .asciiz "Exocite" ; Exocite
ff6vwf_long_enemy_name_058: .asciiz "Anguiform" ; Anguiform
ff6vwf_long_enemy_name_059: .asciiz "Leap Frog" ; Reach Frog
ff6vwf_long_enemy_name_060: .asciiz "Lizard" ; Lizard
ff6vwf_long_enemy_name_061: .asciiz "Litwor Chicken" ; ChickenLip
ff6vwf_long_enemy_name_062: .asciiz "Slagworm" ; Hoover
ff6vwf_long_enemy_name_063: .asciiz "Hell's Rider" ; Rider
ff6vwf_long_enemy_name_064: .asciiz "Typhon" ; Chupon
ff6vwf_long_enemy_name_065: .asciiz "Onion Knight" ; Pipsqueak
ff6vwf_long_enemy_name_066: .asciiz "Magitek Armor" ; M-TekArmor
ff6vwf_long_enemy_name_067: .asciiz "Sky Armor" ; Sky Armor
ff6vwf_long_enemy_name_068: .asciiz "Satellite" ; Telstar
ff6vwf_long_enemy_name_069: .asciiz "Armored Weapon" ; Lethal Wpn
ff6vwf_long_enemy_name_070: .asciiz "Spritzer" ; Vaporite
ff6vwf_long_enemy_name_071: .asciiz "Flan" ; Flan
ff6vwf_long_enemy_name_072: .asciiz "Outcast" ; Ing
ff6vwf_long_enemy_name_073: .asciiz "Humpty" ; Humpty
ff6vwf_long_enemy_name_074: .asciiz "Brainpan" ; Brainpan
ff6vwf_long_enemy_name_075: .asciiz "Cruller" ; Cruller
ff6vwf_long_enemy_name_076: .asciiz "Cactuar" ; Cactrot
ff6vwf_long_enemy_name_077: .asciiz "Bandit" ; Repo Man
ff6vwf_long_enemy_name_078: .asciiz "Harvester" ; Harvester
ff6vwf_long_enemy_name_079: .asciiz "Bomb" ; Bomb
ff6vwf_long_enemy_name_080: .asciiz "Still Life" ; Still Life
ff6vwf_long_enemy_name_081: .asciiz "Lunatys" ; Boxed Set
ff6vwf_long_enemy_name_082: .asciiz "Veil Dancer" ; SlamDancer
ff6vwf_long_enemy_name_083: .asciiz "Hill Gigas" ; HadesGigas
ff6vwf_long_enemy_name_084: .asciiz "Tonberry" ; Pug
ff6vwf_long_enemy_name_085: .asciiz "Magic Urn" ; Magic Urn
ff6vwf_long_enemy_name_086: .asciiz "Mover" ; Mover
ff6vwf_long_enemy_name_087: .asciiz "Figaro Lizard" ; Figaliz
ff6vwf_long_enemy_name_088: .asciiz "Devoahan" ; Buffalax
ff6vwf_long_enemy_name_089: .asciiz "Aspiran" ; Aspik
ff6vwf_long_enemy_name_090: .asciiz "Ghost" ; Ghost
ff6vwf_long_enemy_name_091: .asciiz "Crawler" ; Crawler
ff6vwf_long_enemy_name_092: .asciiz "Sand Ray" ; Sand Ray
ff6vwf_long_enemy_name_093: .asciiz "Alacran" ; Areneid
ff6vwf_long_enemy_name_094: .asciiz "Actinian" ; Actaneon
ff6vwf_long_enemy_name_095: .asciiz "Sandhorse" ; Sand Horse
ff6vwf_long_enemy_name_096: .asciiz "Darkside" ; Dark Side
ff6vwf_long_enemy_name_097: .asciiz "Malboro" ; Mad Oscar
ff6vwf_long_enemy_name_098: .asciiz "Urok" ; Crawly
ff6vwf_long_enemy_name_099: .asciiz "Foper" ; Bleary
ff6vwf_long_enemy_name_100: .asciiz "Guard Leader" ; Marshal
ff6vwf_long_enemy_name_101: .asciiz "Corporal" ; Trooper
ff6vwf_long_enemy_name_102: .asciiz "General" ; General
ff6vwf_long_enemy_name_103: .asciiz "Covert" ; Covert
ff6vwf_long_enemy_name_104: .asciiz "Kamui" ; Ogor
ff6vwf_long_enemy_name_105: .asciiz "Warlock" ; Warlock
ff6vwf_long_enemy_name_106: .asciiz "Cherry" ; Madam
ff6vwf_long_enemy_name_107: .asciiz "Joker" ; Joker
ff6vwf_long_enemy_name_108: .asciiz "Iron Fist" ; Iron Fist
ff6vwf_long_enemy_name_109: .asciiz "Devil" ; Goblin
ff6vwf_long_enemy_name_110: .asciiz "Provoker" ; Apparite
ff6vwf_long_enemy_name_111: .asciiz "Cloudwraith" ; PowerDemon
ff6vwf_long_enemy_name_112: .asciiz "Mahadeva" ; Displayer
ff6vwf_long_enemy_name_113: .asciiz "Vector Hound" ; Vector Pup
ff6vwf_long_enemy_name_114: .asciiz "Peeper" ; Peepers
ff6vwf_long_enemy_name_115: .asciiz "Sewer Rat" ; Sewer Rat
ff6vwf_long_enemy_name_116: .asciiz "Sorath" ; Slatter
ff6vwf_long_enemy_name_117: .asciiz "Destroyer" ; Rhinox
ff6vwf_long_enemy_name_118: .asciiz "Chippirabbit" ; Rhobite
ff6vwf_long_enemy_name_119: .asciiz "Coeurl Cat" ; Wild Cat
ff6vwf_long_enemy_name_120: .asciiz "Bloodfang" ; Red Fang
ff6vwf_long_enemy_name_121: .asciiz "Hunting Hound" ; Bounty Man
ff6vwf_long_enemy_name_122: .asciiz "Gorgias" ; Tusker
ff6vwf_long_enemy_name_123: .asciiz "Don" ; Ralph
ff6vwf_long_enemy_name_124: .asciiz "Murussu" ; Chitonid
ff6vwf_long_enemy_name_125: .asciiz "Wartpuck" ; Wart Puck
ff6vwf_long_enemy_name_126: .asciiz "Gorgimera" ; Rhyos
ff6vwf_long_enemy_name_127: .asciiz "Behemoth King" ; SrBehemoth
ff6vwf_long_enemy_name_128: .asciiz "Vector Lythos" ; Vectaur
ff6vwf_long_enemy_name_129: .asciiz "Wyvern" ; Wyvern
ff6vwf_long_enemy_name_130: .asciiz "Zombie Dragon" ; Zombone
ff6vwf_long_enemy_name_131: .asciiz "Dragon" ; Dragon
ff6vwf_long_enemy_name_132: .asciiz "Primeval Dragon" ; Brontaur
ff6vwf_long_enemy_name_133: .asciiz "Weredragon" ; Allosaurus
ff6vwf_long_enemy_name_134: .asciiz "Cirpius" ; Cirpius
ff6vwf_long_enemy_name_135: .asciiz "Sprinter" ; Sprinter
ff6vwf_long_enemy_name_136: .asciiz "Lenergia" ; Gobbler
ff6vwf_long_enemy_name_137: .asciiz "Marchosias" ; Harpiai
ff6vwf_long_enemy_name_138: .asciiz "Gloomwind" ; GloomShell
ff6vwf_long_enemy_name_139: .asciiz "Dropper" ; Drop
ff6vwf_long_enemy_name_140: .asciiz "Rock Wasp" ; Mind Candy
ff6vwf_long_enemy_name_141: .asciiz "Grasswyrm" ; WeedFeeder
ff6vwf_long_enemy_name_142: .asciiz "Luridan" ; Luridan
ff6vwf_long_enemy_name_143: .asciiz "Twinscythe" ; Toe Cutter
ff6vwf_long_enemy_name_144: .asciiz "Paraladia" ; Over Grunk
ff6vwf_long_enemy_name_145: .asciiz "Exoray" ; Exoray
ff6vwf_long_enemy_name_146: .asciiz "Crusher" ; Crusher
ff6vwf_long_enemy_name_147: .asciiz "Ouroboros" ; Uroburos
ff6vwf_long_enemy_name_148: .asciiz "Acrophies" ; Primordite
ff6vwf_long_enemy_name_149: .asciiz "Schmidt" ; Sky Cap
ff6vwf_long_enemy_name_150: .asciiz "Devourer" ; Cephaler
ff6vwf_long_enemy_name_151: .asciiz "Cancer" ; Maliga
ff6vwf_long_enemy_name_152: .asciiz "Gigantoad" ; Gigan Toad
ff6vwf_long_enemy_name_153: .asciiz "Basilisk" ; Geckorex
ff6vwf_long_enemy_name_154: .asciiz "Medusa Chicken" ; Cluck
ff6vwf_long_enemy_name_155: .asciiz "Landworm" ; Land Worm
ff6vwf_long_enemy_name_156: .asciiz "Test Rider" ; Test Rider
ff6vwf_long_enemy_name_157: .asciiz "Pluto Armor" ; PlutoArmor
ff6vwf_long_enemy_name_158: .asciiz "Onion Dasher" ; Tomb Thumb
ff6vwf_long_enemy_name_159: .asciiz "Heavy Armor" ; HeavyArmor
ff6vwf_long_enemy_name_160: .asciiz "Chaser" ; Chaser
ff6vwf_long_enemy_name_161: .asciiz "Gamma" ; Scullion
ff6vwf_long_enemy_name_162: .asciiz "Poplium" ; Poplium
ff6vwf_long_enemy_name_163: .asciiz "Intangir" ; Intangir
ff6vwf_long_enemy_name_164: .asciiz "Misfit" ; Misfit
ff6vwf_long_enemy_name_165: .asciiz "Creature" ; Eland
ff6vwf_long_enemy_name_166: .asciiz "Enuo" ; Enuo
ff6vwf_long_enemy_name_167: .asciiz "Deepeye" ; Deep Eye
ff6vwf_long_enemy_name_168: .asciiz "Unseelie" ; GreaseMonk
ff6vwf_long_enemy_name_169: .asciiz "Neck Hunter" ; NeckHunter
ff6vwf_long_enemy_name_170: .asciiz "Grenade" ; Grenade
ff6vwf_long_enemy_name_171: .asciiz "Alluring Rider" ; Critic
ff6vwf_long_enemy_name_172: .asciiz "Pandora" ; Pan Dora
ff6vwf_long_enemy_name_173: .asciiz "Blade Dancer" ; SoulDancer
ff6vwf_long_enemy_name_174: .asciiz "Gigantos" ; Gigantos
ff6vwf_long_enemy_name_175: .asciiz "Magna Roader" ; Mag Roader
ff6vwf_long_enemy_name_176: .asciiz "Lycaon" ; Spek Tor
ff6vwf_long_enemy_name_177: .asciiz "Parasite" ; Parasite
ff6vwf_long_enemy_name_178: .asciiz "Land Ray" ; EarthGuard
ff6vwf_long_enemy_name_179: .asciiz "Antares" ; Coelecite
ff6vwf_long_enemy_name_180: .asciiz "Anemone" ; Anemone
ff6vwf_long_enemy_name_181: .asciiz "Moonform" ; Hipocampus
ff6vwf_long_enemy_name_182: .asciiz "Spectre" ; Spectre
ff6vwf_long_enemy_name_183: .asciiz "Great Malboro" ; Evil Oscar
ff6vwf_long_enemy_name_184: .asciiz "Bonnacon" ; Slurm
ff6vwf_long_enemy_name_185: .asciiz "Oceanus" ; Latimeria
ff6vwf_long_enemy_name_186: .asciiz "Living Dead" ; StillGoing
ff6vwf_long_enemy_name_187: .asciiz "Death Warden" ; Allo Ver
ff6vwf_long_enemy_name_188: .asciiz "Face" ; Phase
ff6vwf_long_enemy_name_189: .asciiz "Outsider" ; Outsider
ff6vwf_long_enemy_name_190: .asciiz "Coco" ; Barb-e
ff6vwf_long_enemy_name_191: .asciiz "Zeveak" ; Parasoul
ff6vwf_long_enemy_name_192: .asciiz "Nightwalker" ; Pm Stalker
ff6vwf_long_enemy_name_193: .asciiz "Demon Knight" ; Hemophyte
ff6vwf_long_enemy_name_194: .asciiz "Imperial Elite" ; Sp Forces
ff6vwf_long_enemy_name_195: .asciiz "Desert Hare" ; Nohrabbit
ff6vwf_long_enemy_name_196: .asciiz "Wizard" ; Wizard
ff6vwf_long_enemy_name_197: .asciiz "Devil Fist" ; Scrapper
ff6vwf_long_enemy_name_198: .asciiz "Illuyankas" ; Ceritops
ff6vwf_long_enemy_name_199: .asciiz "Sergeant" ; Commando
ff6vwf_long_enemy_name_200: .asciiz "Aspidochelon" ; Opinicus
ff6vwf_long_enemy_name_201: .asciiz "Knotty" ; Poppers
ff6vwf_long_enemy_name_202: .asciiz "Luna Wolf" ; Lunaris
ff6vwf_long_enemy_name_203: .asciiz "Belzecue" ; Garm
ff6vwf_long_enemy_name_204: .asciiz "Caladrius" ; Vindr
ff6vwf_long_enemy_name_205: .asciiz "Tzakmaqiel" ; Kiwok
ff6vwf_long_enemy_name_206: .asciiz "Lukhavi" ; Nastidon
ff6vwf_long_enemy_name_207: .asciiz "Eukaryote" ; Rinn
ff6vwf_long_enemy_name_208: .asciiz "Land Grillon" ; Insecare
ff6vwf_long_enemy_name_209: .asciiz "Goetia" ; Vermin
ff6vwf_long_enemy_name_210: .asciiz "Greater Mantis" ; Mantodea
ff6vwf_long_enemy_name_211: .asciiz "Bogy" ; Bogy
ff6vwf_long_enemy_name_212: .asciiz "Purusa" ; Prussian
ff6vwf_long_enemy_name_213: .asciiz "Black Dragon" ; Black Drgn
ff6vwf_long_enemy_name_214: .asciiz "Adamankary" ; Adamanchyt
ff6vwf_long_enemy_name_215: .asciiz "Dante" ; Dante
ff6vwf_long_enemy_name_216: .asciiz "Platinum Dragon" ; Wirey Drgn
ff6vwf_long_enemy_name_217: .asciiz "Duel Armor" ; Dueller
ff6vwf_long_enemy_name_218: .asciiz "Psychos" ; Psychot
ff6vwf_long_enemy_name_219: .asciiz "Mousse" ; Muus
ff6vwf_long_enemy_name_220: .asciiz "Shambling Corpse" ; Karkass
ff6vwf_long_enemy_name_221: .asciiz "Punisher" ; Punisher
ff6vwf_long_enemy_name_222: .asciiz "Balloon" ; Balloon
ff6vwf_long_enemy_name_223: .asciiz "Gobbledygook" ; Gabbldegak
ff6vwf_long_enemy_name_224: .asciiz "Great Behemoth" ; GtBehemoth
ff6vwf_long_enemy_name_225: .asciiz "Scorpion" ; Scorpion
ff6vwf_long_enemy_name_226: .asciiz "Chaos Dragon" ; Chaos Drgn
ff6vwf_long_enemy_name_227: .asciiz "Spitfire" ; Spit Fire
ff6vwf_long_enemy_name_228: .asciiz "Vector Chimera" ; Vectagoyle
ff6vwf_long_enemy_name_229: .asciiz "Lich" ; Lich
ff6vwf_long_enemy_name_230: .asciiz "Rukh" ; Osprey
ff6vwf_long_enemy_name_231: .asciiz "Magna Roader" ; Mag Roader
ff6vwf_long_enemy_name_232: .asciiz "Bug" ; Bug
ff6vwf_long_enemy_name_233: .asciiz "Seaflower" ; Sea Flower
ff6vwf_long_enemy_name_234: .asciiz "Fortis" ; Fortis
ff6vwf_long_enemy_name_235: .asciiz "Venobennu" ; Abolisher
ff6vwf_long_enemy_name_236: .asciiz "Galypdes" ; Aquila
ff6vwf_long_enemy_name_237: .asciiz "Junk" ; Junk
ff6vwf_long_enemy_name_238: .asciiz "Mandrake" ; Mandrake
ff6vwf_long_enemy_name_239: .asciiz "Valeor" ; 1st Class
ff6vwf_long_enemy_name_240: .asciiz "Amduscias" ; Tap Dancer
ff6vwf_long_enemy_name_241: .asciiz "Necromancer" ; Necromancr
ff6vwf_long_enemy_name_242: .asciiz "Glasya Labolas" ; Borras
ff6vwf_long_enemy_name_243: .asciiz "Magna Roader" ; Mag Roader
ff6vwf_long_enemy_name_244: .asciiz "Wild Rat" ; Wild Rat
ff6vwf_long_enemy_name_245: .asciiz "Gold Bear" ; Gold Bear
ff6vwf_long_enemy_name_246: .asciiz "InnoSent" ; Innoc
ff6vwf_long_enemy_name_247: .asciiz "Clymenus" ; Trixter
ff6vwf_long_enemy_name_248: .asciiz "Garm" ; Red Wolf
ff6vwf_long_enemy_name_249: .asciiz "Daedalus" ; Didalos
ff6vwf_long_enemy_name_250: .asciiz "Baalzephon" ; Woolly
ff6vwf_long_enemy_name_251: .asciiz "Ahriman" ; Veteran
ff6vwf_long_enemy_name_252: .asciiz "Death Machine" ; Sky Base
ff6vwf_long_enemy_name_253: .asciiz "Metal Hitman" ; IronHitman
ff6vwf_long_enemy_name_254: .asciiz "Io" ; Io
ff6vwf_long_enemy_name_255: .asciiz "Tonberries" ; Pugs
ff6vwf_long_enemy_name_256: .asciiz "Ymir" ; Whelk
ff6vwf_long_enemy_name_257: .asciiz "Angler Whelk" ; Presenter
ff6vwf_long_enemy_name_258: .asciiz "Mega Armor" ; Mega Armor
ff6vwf_long_enemy_name_259: .asciiz "Vargas" ; Vargas
ff6vwf_long_enemy_name_260: .asciiz "Tunnel Armor" ; TunnelArmr
ff6vwf_long_enemy_name_261: .asciiz "Prometheus" ; Prometheus
ff6vwf_long_enemy_name_262: .asciiz "Phantom Train" ; GhostTrain
ff6vwf_long_enemy_name_263: .asciiz "Dadaluma" ; Dadaluma
ff6vwf_long_enemy_name_264: .asciiz "Shiva" ; Shiva
ff6vwf_long_enemy_name_265: .asciiz "Ifrit" ; Ifrit
ff6vwf_long_enemy_name_266: .asciiz "Number 024" ; Number 024
ff6vwf_long_enemy_name_267: .asciiz "Number 128" ; Number 128
ff6vwf_long_enemy_name_268: .asciiz "Inferno" ; Inferno
ff6vwf_long_enemy_name_269: .asciiz "Crane" ; Crane
ff6vwf_long_enemy_name_270: .asciiz "Crane" ; Crane
ff6vwf_long_enemy_name_271: .asciiz "Umaro" ; Umaro
ff6vwf_long_enemy_name_272: .asciiz "Umaro" ; Umaro
ff6vwf_long_enemy_name_273: .asciiz "Guardian" ; Guardian
ff6vwf_long_enemy_name_274: .asciiz "Guardian" ; Guardian
ff6vwf_long_enemy_name_275: .asciiz "Air Force" ; Air Force
ff6vwf_long_enemy_name_276: .asciiz "Valigarmanda" ; Tritoch
ff6vwf_long_enemy_name_277: .asciiz "Valigarmanda" ; Tritoch
ff6vwf_long_enemy_name_278: .asciiz "Flame Eater" ; FlameEater
ff6vwf_long_enemy_name_279: .asciiz "Ultima Weapon" ; AtmaWeapon
ff6vwf_long_enemy_name_280: .asciiz "Nelapa" ; Nerapa
ff6vwf_long_enemy_name_281: .asciiz "Behemoth King" ; SrBehemoth
ff6vwf_long_enemy_name_282: .asciiz "Kefka" ; Kefka
ff6vwf_long_enemy_name_283: .asciiz "Tentacle" ; Tentacle
ff6vwf_long_enemy_name_284: .asciiz "Dullahan" ; Dullahan
ff6vwf_long_enemy_name_285: .asciiz "Deathgaze" ; Doom Gaze
ff6vwf_long_enemy_name_286: .asciiz "Chadarnook" ; Chadarnook
ff6vwf_long_enemy_name_287: .asciiz "Curlax" ; Curley
ff6vwf_long_enemy_name_288: .asciiz "Laragorn" ; Larry
ff6vwf_long_enemy_name_289: .asciiz "Moebius" ; Moe
ff6vwf_long_enemy_name_290: .asciiz "Wrexsoul" ; Wrexsoul
ff6vwf_long_enemy_name_291: .asciiz "Hidon" ; Hidon
ff6vwf_long_enemy_name_292: .asciiz "Samurai Soul" ; KatanaSoul
ff6vwf_long_enemy_name_293: .asciiz "Level 30 Magic" ; L.30 Magic
ff6vwf_long_enemy_name_294: .asciiz "Hidonite" ; Hidonite
ff6vwf_long_enemy_name_295: .asciiz "Fiend" ; Doom
ff6vwf_long_enemy_name_296: .asciiz "Goddess" ; Goddess
ff6vwf_long_enemy_name_297: .asciiz "Demon" ; Poltrgeist
ff6vwf_long_enemy_name_298: .asciiz "Kefka" ; Kefka
ff6vwf_long_enemy_name_299: .asciiz "Level 40 Magic" ; L.40 Magic
ff6vwf_long_enemy_name_300: .asciiz "Ultros" ; Ultros
ff6vwf_long_enemy_name_301: .asciiz "Ultros" ; Ultros
ff6vwf_long_enemy_name_302: .asciiz "Ultros" ; Ultros
ff6vwf_long_enemy_name_303: .asciiz "Typhon" ; Chupon
ff6vwf_long_enemy_name_304: .asciiz "Level 20 Magic" ; L.20 Magic
ff6vwf_long_enemy_name_305: .asciiz "Siegfried" ; Siegfried
ff6vwf_long_enemy_name_306: .asciiz "Level 10 Magic" ; L.10 Magic
ff6vwf_long_enemy_name_307: .asciiz "Level 50 Magic" ; L.50 Magic
ff6vwf_long_enemy_name_308: .asciiz "Head" ; Head
ff6vwf_long_enemy_name_309: .asciiz "Ymir Head" ; Whelk Head
ff6vwf_long_enemy_name_310: .asciiz "Colossus" ; Colossus
ff6vwf_long_enemy_name_311: .asciiz "Czar Dragon" ; CzarDragon
ff6vwf_long_enemy_name_312: .asciiz "Master Tonberry" ; Master Pug
ff6vwf_long_enemy_name_313: .asciiz "Level 60 Magic" ; L.60 Magic
ff6vwf_long_enemy_name_314: .asciiz "Merchant" ; Merchant
ff6vwf_long_enemy_name_315: .asciiz "Birthday Suit" ; B.Day Suit
ff6vwf_long_enemy_name_316: .asciiz "Tentacle" ; Tentacle
ff6vwf_long_enemy_name_317: .asciiz "Tentacle" ; Tentacle
ff6vwf_long_enemy_name_318: .asciiz "Tentacle" ; Tentacle
ff6vwf_long_enemy_name_319: .asciiz "Right Blade" ; RightBlade
ff6vwf_long_enemy_name_320: .asciiz "Left Blade" ; Left Blade
ff6vwf_long_enemy_name_321: .asciiz "Rahu" ; Rough
ff6vwf_long_enemy_name_322: .asciiz "Ketu" ; Striker
ff6vwf_long_enemy_name_323: .asciiz "Level 70 Magic" ; L.70 Magic
ff6vwf_long_enemy_name_324: .asciiz "Valigarmanda" ; Tritoch
ff6vwf_long_enemy_name_325: .asciiz "Laser Gun" ; Laser Gun
ff6vwf_long_enemy_name_326: .asciiz "Bit" ; Speck
ff6vwf_long_enemy_name_327: .asciiz "Missile Bay" ; MissileBay
ff6vwf_long_enemy_name_328: .asciiz "Chadarnook" ; Chadarnook
ff6vwf_long_enemy_name_329: .asciiz "Ice Dragon" ; Ice Dragon
ff6vwf_long_enemy_name_330: .asciiz "Kefka" ; Kefka
ff6vwf_long_enemy_name_331: .asciiz "Storm Dragon" ; Storm Drgn
ff6vwf_long_enemy_name_332: .asciiz "Earth Dragon" ; Dirt Drgn
ff6vwf_long_enemy_name_333: .asciiz "Ipooh" ; Ipooh
ff6vwf_long_enemy_name_334: .asciiz "Leader" ; Leader
ff6vwf_long_enemy_name_335: .asciiz "Grunt" ; Grunt
ff6vwf_long_enemy_name_336: .asciiz "Gold Dragon" ; Gold Drgn
ff6vwf_long_enemy_name_337: .asciiz "Skull Dragon" ; Skull Drgn
ff6vwf_long_enemy_name_338: .asciiz "Blue Dragon" ; Blue Drgn
ff6vwf_long_enemy_name_339: .asciiz "Red Dragon" ; Red Dragon
ff6vwf_long_enemy_name_340: .asciiz "Opinicus Fish" ; Piranha
ff6vwf_long_enemy_name_341: .asciiz "Rhizopas" ; Rizopas
ff6vwf_long_enemy_name_342: .asciiz "Apparition" ; Specter
ff6vwf_long_enemy_name_343: .asciiz "Short Arm" ; Short Arm
ff6vwf_long_enemy_name_344: .asciiz "Long Arm" ; Long Arm
ff6vwf_long_enemy_name_345: .asciiz "Face" ; Face
ff6vwf_long_enemy_name_346: .asciiz "Tiger" ; Tiger
ff6vwf_long_enemy_name_347: .asciiz "Tools" ; Tools
ff6vwf_long_enemy_name_348: .asciiz "Magic" ; Magic
ff6vwf_long_enemy_name_349: .asciiz "Hit" ; Hit
ff6vwf_long_enemy_name_350: .asciiz "Girl" ; Girl
ff6vwf_long_enemy_name_351: .asciiz "Sleep" ; Sleep
ff6vwf_long_enemy_name_352: .asciiz "Hidonite" ; Hidonite
ff6vwf_long_enemy_name_353: .asciiz "Hidonite" ; Hidonite
ff6vwf_long_enemy_name_354: .asciiz "Hidonite" ; Hidonite
ff6vwf_long_enemy_name_355: .asciiz "Level 80 Magic" ; L.80 Magic
ff6vwf_long_enemy_name_356: .asciiz "Level 90 Magic" ; L.90 Magic
ff6vwf_long_enemy_name_357: .asciiz "Proto Armor" ; ProtoArmor
ff6vwf_long_enemy_name_358: .asciiz "Magic Master" ; MagiMaster
ff6vwf_long_enemy_name_359: .asciiz "Soul Saver" ; SoulSaver
ff6vwf_long_enemy_name_360: .asciiz "Ultros" ; Ultros
ff6vwf_long_enemy_name_361: .asciiz "Naude" ; Naughty
ff6vwf_long_enemy_name_362: .asciiz "Humbaba" ; Phunbaba
ff6vwf_long_enemy_name_363: .asciiz "Humbaba" ; Phunbaba
ff6vwf_long_enemy_name_364: .asciiz "Humbaba" ; Phunbaba
ff6vwf_long_enemy_name_365: .asciiz "Humbaba" ; Phunbaba
ff6vwf_long_enemy_name_366: .asciiz "" ; 
ff6vwf_long_enemy_name_367: .asciiz "" ; 
ff6vwf_long_enemy_name_368: .asciiz "" ; 
ff6vwf_long_enemy_name_369: .asciiz "Zone Eater" ; Zone Eater
ff6vwf_long_enemy_name_370: .asciiz "" ; 
ff6vwf_long_enemy_name_371: .asciiz "" ; 
ff6vwf_long_enemy_name_372: .asciiz "" ; 
ff6vwf_long_enemy_name_373: .asciiz "Officer" ; Officer
ff6vwf_long_enemy_name_374: .asciiz "Cadet" ; Cadet
ff6vwf_long_enemy_name_375: .asciiz "" ; 
ff6vwf_long_enemy_name_376: .asciiz "" ; 
ff6vwf_long_enemy_name_377: .asciiz "Soldier" ; Soldier
ff6vwf_long_enemy_name_378: .asciiz "" ; 
ff6vwf_long_enemy_name_379: .asciiz "" ; 
ff6vwf_long_enemy_name_380: .asciiz "" ; 
ff6vwf_long_enemy_name_381: .asciiz "Ultima" ; Atma
ff6vwf_long_enemy_name_382: .asciiz "" ; 
ff6vwf_long_enemy_name_383: .asciiz "" ; 
ff6vwf_long_enemy_name_384: .asciiz "" ; 
ff6vwf_long_enemy_name_385: .asciiz "" ; 
ff6vwf_long_enemy_name_386: .asciiz "" ; 
ff6vwf_long_enemy_name_387: .asciiz "" ; 
ff6vwf_long_enemy_name_388: .asciiz "" ; 
ff6vwf_long_enemy_name_389: .asciiz "" ; 
ff6vwf_long_enemy_name_390: .asciiz "" ; 
ff6vwf_long_enemy_name_391: .asciiz "" ; 
ff6vwf_long_enemy_name_392: .asciiz "" ; 
ff6vwf_long_enemy_name_393: .asciiz "" ; 
ff6vwf_long_enemy_name_394: .asciiz "" ; 
ff6vwf_long_enemy_name_395: .asciiz "" ; 
ff6vwf_long_enemy_name_396: .asciiz "" ; 
ff6vwf_long_enemy_name_397: .asciiz "" ; 
ff6vwf_long_enemy_name_398: .asciiz "" ; 
ff6vwf_long_enemy_name_399: .asciiz "" ; 
ff6vwf_long_enemy_name_400: .asciiz "" ; 
ff6vwf_long_enemy_name_401: .asciiz "" ; 
ff6vwf_long_enemy_name_402: .asciiz "" ; 
ff6vwf_long_enemy_name_403: .asciiz "" ; 
ff6vwf_long_enemy_name_404: .asciiz "" ; 
ff6vwf_long_enemy_name_405: .asciiz "" ; 
ff6vwf_long_enemy_name_406: .asciiz "" ; 
ff6vwf_long_enemy_name_407: .asciiz "" ; 
ff6vwf_long_enemy_name_408: .asciiz "" ; 
ff6vwf_long_enemy_name_409: .asciiz "" ; 
ff6vwf_long_enemy_name_410: .asciiz "" ; 
ff6vwf_long_enemy_name_411: .asciiz "" ; 
ff6vwf_long_enemy_name_412: .asciiz "" ; 
ff6vwf_long_enemy_name_413: .asciiz "" ; 
ff6vwf_long_enemy_name_414: .asciiz "" ; 
ff6vwf_long_enemy_name_415: .asciiz "" ; 
ff6vwf_long_enemy_name_416: .asciiz "" ; 
ff6vwf_long_enemy_name_417: .asciiz "" ; 
ff6vwf_long_enemy_name_418: .asciiz "" ; 
ff6vwf_long_enemy_name_419: .asciiz "" ; 
ff6vwf_long_enemy_name_420: .asciiz "" ; 
ff6vwf_long_enemy_name_421: .asciiz "" ; 
