.segment "DATA"

ff6vwf_long_item_names:
    .word .loword(ff6vwf_long_item_name_000)
    .word .loword(ff6vwf_long_item_name_001)
    .word .loword(ff6vwf_long_item_name_002)
    .word .loword(ff6vwf_long_item_name_003)
    .word .loword(ff6vwf_long_item_name_004)
    .word .loword(ff6vwf_long_item_name_005)
    .word .loword(ff6vwf_long_item_name_006)
    .word .loword(ff6vwf_long_item_name_007)
    .word .loword(ff6vwf_long_item_name_008)
    .word .loword(ff6vwf_long_item_name_009)
    .word .loword(ff6vwf_long_item_name_010)
    .word .loword(ff6vwf_long_item_name_011)
    .word .loword(ff6vwf_long_item_name_012)
    .word .loword(ff6vwf_long_item_name_013)
    .word .loword(ff6vwf_long_item_name_014)
    .word .loword(ff6vwf_long_item_name_015)
    .word .loword(ff6vwf_long_item_name_016)
    .word .loword(ff6vwf_long_item_name_017)
    .word .loword(ff6vwf_long_item_name_018)
    .word .loword(ff6vwf_long_item_name_019)
    .word .loword(ff6vwf_long_item_name_020)
    .word .loword(ff6vwf_long_item_name_021)
    .word .loword(ff6vwf_long_item_name_022)
    .word .loword(ff6vwf_long_item_name_023)
    .word .loword(ff6vwf_long_item_name_024)
    .word .loword(ff6vwf_long_item_name_025)
    .word .loword(ff6vwf_long_item_name_026)
    .word .loword(ff6vwf_long_item_name_027)
    .word .loword(ff6vwf_long_item_name_028)
    .word .loword(ff6vwf_long_item_name_029)
    .word .loword(ff6vwf_long_item_name_030)
    .word .loword(ff6vwf_long_item_name_031)
    .word .loword(ff6vwf_long_item_name_032)
    .word .loword(ff6vwf_long_item_name_033)
    .word .loword(ff6vwf_long_item_name_034)
    .word .loword(ff6vwf_long_item_name_035)
    .word .loword(ff6vwf_long_item_name_036)
    .word .loword(ff6vwf_long_item_name_037)
    .word .loword(ff6vwf_long_item_name_038)
    .word .loword(ff6vwf_long_item_name_039)
    .word .loword(ff6vwf_long_item_name_040)
    .word .loword(ff6vwf_long_item_name_041)
    .word .loword(ff6vwf_long_item_name_042)
    .word .loword(ff6vwf_long_item_name_043)
    .word .loword(ff6vwf_long_item_name_044)
    .word .loword(ff6vwf_long_item_name_045)
    .word .loword(ff6vwf_long_item_name_046)
    .word .loword(ff6vwf_long_item_name_047)
    .word .loword(ff6vwf_long_item_name_048)
    .word .loword(ff6vwf_long_item_name_049)
    .word .loword(ff6vwf_long_item_name_050)
    .word .loword(ff6vwf_long_item_name_051)
    .word .loword(ff6vwf_long_item_name_052)
    .word .loword(ff6vwf_long_item_name_053)
    .word .loword(ff6vwf_long_item_name_054)
    .word .loword(ff6vwf_long_item_name_055)
    .word .loword(ff6vwf_long_item_name_056)
    .word .loword(ff6vwf_long_item_name_057)
    .word .loword(ff6vwf_long_item_name_058)
    .word .loword(ff6vwf_long_item_name_059)
    .word .loword(ff6vwf_long_item_name_060)
    .word .loword(ff6vwf_long_item_name_061)
    .word .loword(ff6vwf_long_item_name_062)
    .word .loword(ff6vwf_long_item_name_063)
    .word .loword(ff6vwf_long_item_name_064)
    .word .loword(ff6vwf_long_item_name_065)
    .word .loword(ff6vwf_long_item_name_066)
    .word .loword(ff6vwf_long_item_name_067)
    .word .loword(ff6vwf_long_item_name_068)
    .word .loword(ff6vwf_long_item_name_069)
    .word .loword(ff6vwf_long_item_name_070)
    .word .loword(ff6vwf_long_item_name_071)
    .word .loword(ff6vwf_long_item_name_072)
    .word .loword(ff6vwf_long_item_name_073)
    .word .loword(ff6vwf_long_item_name_074)
    .word .loword(ff6vwf_long_item_name_075)
    .word .loword(ff6vwf_long_item_name_076)
    .word .loword(ff6vwf_long_item_name_077)
    .word .loword(ff6vwf_long_item_name_078)
    .word .loword(ff6vwf_long_item_name_079)
    .word .loword(ff6vwf_long_item_name_080)
    .word .loword(ff6vwf_long_item_name_081)
    .word .loword(ff6vwf_long_item_name_082)
    .word .loword(ff6vwf_long_item_name_083)
    .word .loword(ff6vwf_long_item_name_084)
    .word .loword(ff6vwf_long_item_name_085)
    .word .loword(ff6vwf_long_item_name_086)
    .word .loword(ff6vwf_long_item_name_087)
    .word .loword(ff6vwf_long_item_name_088)
    .word .loword(ff6vwf_long_item_name_089)
    .word .loword(ff6vwf_long_item_name_090)
    .word .loword(ff6vwf_long_item_name_091)
    .word .loword(ff6vwf_long_item_name_092)
    .word .loword(ff6vwf_long_item_name_093)
    .word .loword(ff6vwf_long_item_name_094)
    .word .loword(ff6vwf_long_item_name_095)
    .word .loword(ff6vwf_long_item_name_096)
    .word .loword(ff6vwf_long_item_name_097)
    .word .loword(ff6vwf_long_item_name_098)
    .word .loword(ff6vwf_long_item_name_099)
    .word .loword(ff6vwf_long_item_name_100)
    .word .loword(ff6vwf_long_item_name_101)
    .word .loword(ff6vwf_long_item_name_102)
    .word .loword(ff6vwf_long_item_name_103)
    .word .loword(ff6vwf_long_item_name_104)
    .word .loword(ff6vwf_long_item_name_105)
    .word .loword(ff6vwf_long_item_name_106)
    .word .loword(ff6vwf_long_item_name_107)
    .word .loword(ff6vwf_long_item_name_108)
    .word .loword(ff6vwf_long_item_name_109)
    .word .loword(ff6vwf_long_item_name_110)
    .word .loword(ff6vwf_long_item_name_111)
    .word .loword(ff6vwf_long_item_name_112)
    .word .loword(ff6vwf_long_item_name_113)
    .word .loword(ff6vwf_long_item_name_114)
    .word .loword(ff6vwf_long_item_name_115)
    .word .loword(ff6vwf_long_item_name_116)
    .word .loword(ff6vwf_long_item_name_117)
    .word .loword(ff6vwf_long_item_name_118)
    .word .loword(ff6vwf_long_item_name_119)
    .word .loword(ff6vwf_long_item_name_120)
    .word .loword(ff6vwf_long_item_name_121)
    .word .loword(ff6vwf_long_item_name_122)
    .word .loword(ff6vwf_long_item_name_123)
    .word .loword(ff6vwf_long_item_name_124)
    .word .loword(ff6vwf_long_item_name_125)
    .word .loword(ff6vwf_long_item_name_126)
    .word .loword(ff6vwf_long_item_name_127)
    .word .loword(ff6vwf_long_item_name_128)
    .word .loword(ff6vwf_long_item_name_129)
    .word .loword(ff6vwf_long_item_name_130)
    .word .loword(ff6vwf_long_item_name_131)
    .word .loword(ff6vwf_long_item_name_132)
    .word .loword(ff6vwf_long_item_name_133)
    .word .loword(ff6vwf_long_item_name_134)
    .word .loword(ff6vwf_long_item_name_135)
    .word .loword(ff6vwf_long_item_name_136)
    .word .loword(ff6vwf_long_item_name_137)
    .word .loword(ff6vwf_long_item_name_138)
    .word .loword(ff6vwf_long_item_name_139)
    .word .loword(ff6vwf_long_item_name_140)
    .word .loword(ff6vwf_long_item_name_141)
    .word .loword(ff6vwf_long_item_name_142)
    .word .loword(ff6vwf_long_item_name_143)
    .word .loword(ff6vwf_long_item_name_144)
    .word .loword(ff6vwf_long_item_name_145)
    .word .loword(ff6vwf_long_item_name_146)
    .word .loword(ff6vwf_long_item_name_147)
    .word .loword(ff6vwf_long_item_name_148)
    .word .loword(ff6vwf_long_item_name_149)
    .word .loword(ff6vwf_long_item_name_150)
    .word .loword(ff6vwf_long_item_name_151)
    .word .loword(ff6vwf_long_item_name_152)
    .word .loword(ff6vwf_long_item_name_153)
    .word .loword(ff6vwf_long_item_name_154)
    .word .loword(ff6vwf_long_item_name_155)
    .word .loword(ff6vwf_long_item_name_156)
    .word .loword(ff6vwf_long_item_name_157)
    .word .loword(ff6vwf_long_item_name_158)
    .word .loword(ff6vwf_long_item_name_159)
    .word .loword(ff6vwf_long_item_name_160)
    .word .loword(ff6vwf_long_item_name_161)
    .word .loword(ff6vwf_long_item_name_162)
    .word .loword(ff6vwf_long_item_name_163)
    .word .loword(ff6vwf_long_item_name_164)
    .word .loword(ff6vwf_long_item_name_165)
    .word .loword(ff6vwf_long_item_name_166)
    .word .loword(ff6vwf_long_item_name_167)
    .word .loword(ff6vwf_long_item_name_168)
    .word .loword(ff6vwf_long_item_name_169)
    .word .loword(ff6vwf_long_item_name_170)
    .word .loword(ff6vwf_long_item_name_171)
    .word .loword(ff6vwf_long_item_name_172)
    .word .loword(ff6vwf_long_item_name_173)
    .word .loword(ff6vwf_long_item_name_174)
    .word .loword(ff6vwf_long_item_name_175)
    .word .loword(ff6vwf_long_item_name_176)
    .word .loword(ff6vwf_long_item_name_177)
    .word .loword(ff6vwf_long_item_name_178)
    .word .loword(ff6vwf_long_item_name_179)
    .word .loword(ff6vwf_long_item_name_180)
    .word .loword(ff6vwf_long_item_name_181)
    .word .loword(ff6vwf_long_item_name_182)
    .word .loword(ff6vwf_long_item_name_183)
    .word .loword(ff6vwf_long_item_name_184)
    .word .loword(ff6vwf_long_item_name_185)
    .word .loword(ff6vwf_long_item_name_186)
    .word .loword(ff6vwf_long_item_name_187)
    .word .loword(ff6vwf_long_item_name_188)
    .word .loword(ff6vwf_long_item_name_189)
    .word .loword(ff6vwf_long_item_name_190)
    .word .loword(ff6vwf_long_item_name_191)
    .word .loword(ff6vwf_long_item_name_192)
    .word .loword(ff6vwf_long_item_name_193)
    .word .loword(ff6vwf_long_item_name_194)
    .word .loword(ff6vwf_long_item_name_195)
    .word .loword(ff6vwf_long_item_name_196)
    .word .loword(ff6vwf_long_item_name_197)
    .word .loword(ff6vwf_long_item_name_198)
    .word .loword(ff6vwf_long_item_name_199)
    .word .loword(ff6vwf_long_item_name_200)
    .word .loword(ff6vwf_long_item_name_201)
    .word .loword(ff6vwf_long_item_name_202)
    .word .loword(ff6vwf_long_item_name_203)
    .word .loword(ff6vwf_long_item_name_204)
    .word .loword(ff6vwf_long_item_name_205)
    .word .loword(ff6vwf_long_item_name_206)
    .word .loword(ff6vwf_long_item_name_207)
    .word .loword(ff6vwf_long_item_name_208)
    .word .loword(ff6vwf_long_item_name_209)
    .word .loword(ff6vwf_long_item_name_210)
    .word .loword(ff6vwf_long_item_name_211)
    .word .loword(ff6vwf_long_item_name_212)
    .word .loword(ff6vwf_long_item_name_213)
    .word .loword(ff6vwf_long_item_name_214)
    .word .loword(ff6vwf_long_item_name_215)
    .word .loword(ff6vwf_long_item_name_216)
    .word .loword(ff6vwf_long_item_name_217)
    .word .loword(ff6vwf_long_item_name_218)
    .word .loword(ff6vwf_long_item_name_219)
    .word .loword(ff6vwf_long_item_name_220)
    .word .loword(ff6vwf_long_item_name_221)
    .word .loword(ff6vwf_long_item_name_222)
    .word .loword(ff6vwf_long_item_name_223)
    .word .loword(ff6vwf_long_item_name_224)
    .word .loword(ff6vwf_long_item_name_225)
    .word .loword(ff6vwf_long_item_name_226)
    .word .loword(ff6vwf_long_item_name_227)
    .word .loword(ff6vwf_long_item_name_228)
    .word .loword(ff6vwf_long_item_name_229)
    .word .loword(ff6vwf_long_item_name_230)
    .word .loword(ff6vwf_long_item_name_231)
    .word .loword(ff6vwf_long_item_name_232)
    .word .loword(ff6vwf_long_item_name_233)
    .word .loword(ff6vwf_long_item_name_234)
    .word .loword(ff6vwf_long_item_name_235)
    .word .loword(ff6vwf_long_item_name_236)
    .word .loword(ff6vwf_long_item_name_237)
    .word .loword(ff6vwf_long_item_name_238)
    .word .loword(ff6vwf_long_item_name_239)
    .word .loword(ff6vwf_long_item_name_240)
    .word .loword(ff6vwf_long_item_name_241)
    .word .loword(ff6vwf_long_item_name_242)
    .word .loword(ff6vwf_long_item_name_243)
    .word .loword(ff6vwf_long_item_name_244)
    .word .loword(ff6vwf_long_item_name_245)
    .word .loword(ff6vwf_long_item_name_246)
    .word .loword(ff6vwf_long_item_name_247)
    .word .loword(ff6vwf_long_item_name_248)
    .word .loword(ff6vwf_long_item_name_249)
    .word .loword(ff6vwf_long_item_name_250)
    .word .loword(ff6vwf_long_item_name_251)
    .word .loword(ff6vwf_long_item_name_252)
    .word .loword(ff6vwf_long_item_name_253)
    .word .loword(ff6vwf_long_item_name_254)
    .word .loword(ff6vwf_long_item_name_255)

ff6vwf_long_item_name_000: .asciiz "Dagger"
ff6vwf_long_item_name_001: .asciiz "Mythril Knife"
ff6vwf_long_item_name_002: .asciiz "Main Gauche"
ff6vwf_long_item_name_003: .asciiz "Air Knife"
ff6vwf_long_item_name_004: .asciiz "Thief's Knife"
ff6vwf_long_item_name_005: .asciiz "Assassin's Dagger"
ff6vwf_long_item_name_006: .asciiz "Man-Eater"
ff6vwf_long_item_name_007: .asciiz "Sword Breaker"
ff6vwf_long_item_name_008: .asciiz "Gladius"
ff6vwf_long_item_name_009: .asciiz "Valiant Knife"
ff6vwf_long_item_name_010: .asciiz "Mythril Sword"
ff6vwf_long_item_name_011: .asciiz "Great Sword"
ff6vwf_long_item_name_012: .asciiz "Rune Blade"
ff6vwf_long_item_name_013: .asciiz "Flametongue"
ff6vwf_long_item_name_014: .asciiz "Icebrand"
ff6vwf_long_item_name_015: .asciiz "Thunder Blade"
ff6vwf_long_item_name_016: .asciiz "Bastard Sword"
ff6vwf_long_item_name_017: .asciiz "Stoneblade"
ff6vwf_long_item_name_018: .asciiz "Blood Sword"
ff6vwf_long_item_name_019: .asciiz "Enhancer"
ff6vwf_long_item_name_020: .asciiz "Crystal Sword"
ff6vwf_long_item_name_021: .asciiz "Falchion"
ff6vwf_long_item_name_022: .asciiz "Soul Sabre"
ff6vwf_long_item_name_023: .asciiz "Organyx"
ff6vwf_long_item_name_024: .asciiz "Excalibur"
ff6vwf_long_item_name_025: .asciiz "Zantetsuken"
ff6vwf_long_item_name_026: .asciiz "Lightbringer"
ff6vwf_long_item_name_027: .asciiz "Ragnarok"
ff6vwf_long_item_name_028: .asciiz "Ultima Weapon"
ff6vwf_long_item_name_029: .asciiz "Mythril Spear"
ff6vwf_long_item_name_030: .asciiz "Trident"
ff6vwf_long_item_name_031: .asciiz "Heavy Lance"
ff6vwf_long_item_name_032: .asciiz "Partisan"
ff6vwf_long_item_name_033: .asciiz "Holy Lance"
ff6vwf_long_item_name_034: .asciiz "Golden Spear"
ff6vwf_long_item_name_035: .asciiz "Radiant Lance"
ff6vwf_long_item_name_036: .asciiz "Impartisan"
ff6vwf_long_item_name_037: .asciiz "Kunai"
ff6vwf_long_item_name_038: .asciiz "Kodachi"
ff6vwf_long_item_name_039: .asciiz "Sakura"
ff6vwf_long_item_name_040: .asciiz "Sasuke"
ff6vwf_long_item_name_041: .asciiz "Ichigeki"
ff6vwf_long_item_name_042: .asciiz "Kagenui"
ff6vwf_long_item_name_043: .asciiz "Ashura"
ff6vwf_long_item_name_044: .asciiz "Kotetsu"
ff6vwf_long_item_name_045: .asciiz "Kiku-ichimonji"
ff6vwf_long_item_name_046: .asciiz "Kazekiri"
ff6vwf_long_item_name_047: .asciiz "Murasame"
ff6vwf_long_item_name_048: .asciiz "Masamune"
ff6vwf_long_item_name_049: .asciiz "Murakumo"
ff6vwf_long_item_name_050: .asciiz "Mutsunokami"
ff6vwf_long_item_name_051: .asciiz "Healing Rod"
ff6vwf_long_item_name_052: .asciiz "Mythril Rod"
ff6vwf_long_item_name_053: .asciiz "Flame Rod"
ff6vwf_long_item_name_054: .asciiz "Ice Rod"
ff6vwf_long_item_name_055: .asciiz "Thunder Rod"
ff6vwf_long_item_name_056: .asciiz "Poison Rod"
ff6vwf_long_item_name_057: .asciiz "Holy Rod"
ff6vwf_long_item_name_058: .asciiz "Gravity Rod"
ff6vwf_long_item_name_059: .asciiz "Punisher"
ff6vwf_long_item_name_060: .asciiz "Magus Rod"
ff6vwf_long_item_name_061: .asciiz "Chocobo Brush"
ff6vwf_long_item_name_062: .asciiz "Da Vinci Brush"
ff6vwf_long_item_name_063: .asciiz "Magical Brush"
ff6vwf_long_item_name_064: .asciiz "Rainbow Brush"
ff6vwf_long_item_name_065: .asciiz "Shuriken"
ff6vwf_long_item_name_066: .asciiz "Fuma Shuriken"
ff6vwf_long_item_name_067: .asciiz "Pinwheel"
ff6vwf_long_item_name_068: .asciiz "Chain Flail"
ff6vwf_long_item_name_069: .asciiz "Moonring Blade"
ff6vwf_long_item_name_070: .asciiz "Morning Star"
ff6vwf_long_item_name_071: .asciiz "Boomerang"
ff6vwf_long_item_name_072: .asciiz "Rising Sun"
ff6vwf_long_item_name_073: .asciiz "Hawkeye"
ff6vwf_long_item_name_074: .asciiz "Bone Club"
ff6vwf_long_item_name_075: .asciiz "Sniper"
ff6vwf_long_item_name_076: .asciiz "Wing Edge"
ff6vwf_long_item_name_077: .asciiz "Cards"
ff6vwf_long_item_name_078: .asciiz "Darts"
ff6vwf_long_item_name_079: .asciiz "Death Tarot"
ff6vwf_long_item_name_080: .asciiz "Viper Darts"
ff6vwf_long_item_name_081: .asciiz "Dice"
ff6vwf_long_item_name_082: .asciiz "Fixed Dice"
ff6vwf_long_item_name_083: .asciiz "Metal Knuckles"
ff6vwf_long_item_name_084: .asciiz "Mythril Claw"
ff6vwf_long_item_name_085: .asciiz "Kaiser Knuckles"
ff6vwf_long_item_name_086: .asciiz "Venom Claws"
ff6vwf_long_item_name_087: .asciiz "Burning Fist"
ff6vwf_long_item_name_088: .asciiz "Dragon Claws"
ff6vwf_long_item_name_089: .asciiz "Tigerfang"
ff6vwf_long_item_name_090: .asciiz "Buckler"
ff6vwf_long_item_name_091: .asciiz "Heavy Shield"
ff6vwf_long_item_name_092: .asciiz "Mythril Shield"
ff6vwf_long_item_name_093: .asciiz "Golden Shield"
ff6vwf_long_item_name_094: .asciiz "Aegis Shield"
ff6vwf_long_item_name_095: .asciiz "Diamond Shield"
ff6vwf_long_item_name_096: .asciiz "Flame Shield"
ff6vwf_long_item_name_097: .asciiz "Ice Shield"
ff6vwf_long_item_name_098: .asciiz "Thunder Shield"
ff6vwf_long_item_name_099: .asciiz "Crystal Shield"
ff6vwf_long_item_name_100: .asciiz "Genji Shield"
ff6vwf_long_item_name_101: .asciiz "Tortoise Shield"
ff6vwf_long_item_name_102: .asciiz "Cursed Shield"
ff6vwf_long_item_name_103: .asciiz "Paladin's Shield"
ff6vwf_long_item_name_104: .asciiz "Force Shield"
ff6vwf_long_item_name_105: .asciiz "Leather Cap"
ff6vwf_long_item_name_106: .asciiz "Hairband"
ff6vwf_long_item_name_107: .asciiz "Plumed Hat"
ff6vwf_long_item_name_108: .asciiz "Beret"
ff6vwf_long_item_name_109: .asciiz "Magus Hat"
ff6vwf_long_item_name_110: .asciiz "Bandana"
ff6vwf_long_item_name_111: .asciiz "Iron Helm"
ff6vwf_long_item_name_112: .asciiz "Hypno Crown"
ff6vwf_long_item_name_113: .asciiz "Priest's Miter"
ff6vwf_long_item_name_114: .asciiz "Green Beret"
ff6vwf_long_item_name_115: .asciiz "Twist Headband"
ff6vwf_long_item_name_116: .asciiz "Mythril Helm"
ff6vwf_long_item_name_117: .asciiz "Tiara"
ff6vwf_long_item_name_118: .asciiz "Golden Helm"
ff6vwf_long_item_name_119: .asciiz "Tiger Mask"
ff6vwf_long_item_name_120: .asciiz "Red Cap"
ff6vwf_long_item_name_121: .asciiz "Mystery Veil"
ff6vwf_long_item_name_122: .asciiz "Circlet"
ff6vwf_long_item_name_123: .asciiz "Royal Crown"
ff6vwf_long_item_name_124: .asciiz "Diamond Helm"
ff6vwf_long_item_name_125: .asciiz "Black Cowl"
ff6vwf_long_item_name_126: .asciiz "Crystal Helm"
ff6vwf_long_item_name_127: .asciiz "Oath Veil"
ff6vwf_long_item_name_128: .asciiz "Cat-Ear Hood"
ff6vwf_long_item_name_129: .asciiz "Genji Helm"
ff6vwf_long_item_name_130: .asciiz "Thornlet"
ff6vwf_long_item_name_131: .asciiz "Saucer"
ff6vwf_long_item_name_132: .asciiz "Leather Armor"
ff6vwf_long_item_name_133: .asciiz "Cotton Robe"
ff6vwf_long_item_name_134: .asciiz "Kenpo Gi"
ff6vwf_long_item_name_135: .asciiz "Iron Armor"
ff6vwf_long_item_name_136: .asciiz "Silk Robe"
ff6vwf_long_item_name_137: .asciiz "Mythril Vest"
ff6vwf_long_item_name_138: .asciiz "Ninja Gear"
ff6vwf_long_item_name_139: .asciiz "White Dress"
ff6vwf_long_item_name_140: .asciiz "Mythril Mail"
ff6vwf_long_item_name_141: .asciiz "Gaia Gear"
ff6vwf_long_item_name_142: .asciiz "Mirage Vest"
ff6vwf_long_item_name_143: .asciiz "Golden Armor"
ff6vwf_long_item_name_144: .asciiz "Power Sash"
ff6vwf_long_item_name_145: .asciiz "Luminous Robe"
ff6vwf_long_item_name_146: .asciiz "Diamond Vest"
ff6vwf_long_item_name_147: .asciiz "Red Jacket"
ff6vwf_long_item_name_148: .asciiz "Force Armor"
ff6vwf_long_item_name_149: .asciiz "Diamond Armor"
ff6vwf_long_item_name_150: .asciiz "Black Garb"
ff6vwf_long_item_name_151: .asciiz "Magus Robe"
ff6vwf_long_item_name_152: .asciiz "Crystal Mail"
ff6vwf_long_item_name_153: .asciiz "Regal Gown"
ff6vwf_long_item_name_154: .asciiz "Genji Armor"
ff6vwf_long_item_name_155: .asciiz "Reed Cloak"
ff6vwf_long_item_name_156: .asciiz "Minerva Bustier"
ff6vwf_long_item_name_157: .asciiz "Tabby Suit"
ff6vwf_long_item_name_158: .asciiz "Chocobo Suit"
ff6vwf_long_item_name_159: .asciiz "Moogle Suit"
ff6vwf_long_item_name_160: .asciiz "Nutkin Suit"
ff6vwf_long_item_name_161: .asciiz "Behemoth Suit"
ff6vwf_long_item_name_162: .asciiz "Snow Scarf"
ff6vwf_long_item_name_163: .asciiz "Noiseblaster"
ff6vwf_long_item_name_164: .asciiz "Bioblaster"
ff6vwf_long_item_name_165: .asciiz "Flash"
ff6vwf_long_item_name_166: .asciiz "Chainsaw"
ff6vwf_long_item_name_167: .asciiz "Debilitator"
ff6vwf_long_item_name_168: .asciiz "Drill"
ff6vwf_long_item_name_169: .asciiz "Air Anchor"
ff6vwf_long_item_name_170: .asciiz "Auto Crossbow"
ff6vwf_long_item_name_171: .asciiz "Flame Scroll"
ff6vwf_long_item_name_172: .asciiz "Water Scroll"
ff6vwf_long_item_name_173: .asciiz "Lightning Scroll"
ff6vwf_long_item_name_174: .asciiz "Invisibility Scroll"
ff6vwf_long_item_name_175: .asciiz "Shadow Scroll"
ff6vwf_long_item_name_176: .asciiz "Silver Spectacles"
ff6vwf_long_item_name_177: .asciiz "Star Pendant"
ff6vwf_long_item_name_178: .asciiz "Peace Ring"
ff6vwf_long_item_name_179: .asciiz "Amulet"
ff6vwf_long_item_name_180: .asciiz "White Cape"
ff6vwf_long_item_name_181: .asciiz "Jeweled Ring"
ff6vwf_long_item_name_182: .asciiz "Fairy Ring"
ff6vwf_long_item_name_183: .asciiz "Barrier Ring"
ff6vwf_long_item_name_184: .asciiz "Mythril Glove"
ff6vwf_long_item_name_185: .asciiz "Protect Ring"
ff6vwf_long_item_name_186: .asciiz "Hermes Sandals"
ff6vwf_long_item_name_187: .asciiz "Reflect Ring"
ff6vwf_long_item_name_188: .asciiz "Angel Wings"
ff6vwf_long_item_name_189: .asciiz "Angel Ring"
ff6vwf_long_item_name_190: .asciiz "Knight's Code"
ff6vwf_long_item_name_191: .asciiz "Dragoon Boots"
ff6vwf_long_item_name_192: .asciiz "Zephyr Cloak"
ff6vwf_long_item_name_193: .asciiz "Princess Ring"
ff6vwf_long_item_name_194: .asciiz "Cursed Ring"
ff6vwf_long_item_name_195: .asciiz "Earring"
ff6vwf_long_item_name_196: .asciiz "Gigas Glove"
ff6vwf_long_item_name_197: .asciiz "Blizzard Orb"
ff6vwf_long_item_name_198: .asciiz "Berserker Ring"
ff6vwf_long_item_name_199: .asciiz "Thief's Bracer"
ff6vwf_long_item_name_200: .asciiz "Guard Bracelet"
ff6vwf_long_item_name_201: .asciiz "Hero's Ring"
ff6vwf_long_item_name_202: .asciiz "Ribbon"
ff6vwf_long_item_name_203: .asciiz "Muscle Belt"
ff6vwf_long_item_name_204: .asciiz "Crystal Orb"
ff6vwf_long_item_name_205: .asciiz "Gold Hairpin"
ff6vwf_long_item_name_206: .asciiz "Celestriad"
ff6vwf_long_item_name_207: .asciiz "Brigand's Glove"
ff6vwf_long_item_name_208: .asciiz "Gauntlet"
ff6vwf_long_item_name_209: .asciiz "Genji Glove"
ff6vwf_long_item_name_210: .asciiz "Hyper Wrist"
ff6vwf_long_item_name_211: .asciiz "Master's Scroll"
ff6vwf_long_item_name_212: .asciiz "Prayer Beads"
ff6vwf_long_item_name_213: .asciiz "Black Belt"
ff6vwf_long_item_name_214: .asciiz "Heiji's Jitte"
ff6vwf_long_item_name_215: .asciiz "Fake Mustache"
ff6vwf_long_item_name_216: .asciiz "Soul of Thamasa"
ff6vwf_long_item_name_217: .asciiz "Dragon Horn"
ff6vwf_long_item_name_218: .asciiz "Merit Award"
ff6vwf_long_item_name_219: .asciiz "Memento Ring"
ff6vwf_long_item_name_220: .asciiz "Safety Bit"
ff6vwf_long_item_name_221: .asciiz "Lich Ring"
ff6vwf_long_item_name_222: .asciiz "Molulu's Charm"
ff6vwf_long_item_name_223: .asciiz "Ward Bangle"
ff6vwf_long_item_name_224: .asciiz "Miracle Shoes"
ff6vwf_long_item_name_225: .asciiz "Alarm Earring"
ff6vwf_long_item_name_226: .asciiz "Gale Hairpin"
ff6vwf_long_item_name_227: .asciiz "Sniper Eye"
ff6vwf_long_item_name_228: .asciiz "Growth Egg"
ff6vwf_long_item_name_229: .asciiz "Tintinnabulum"
ff6vwf_long_item_name_230: .asciiz "Sprint Shoes"
ff6vwf_long_item_name_231: .asciiz "Rename Card"
ff6vwf_long_item_name_232: .asciiz "Potion"
ff6vwf_long_item_name_233: .asciiz "Hi-Potion"
ff6vwf_long_item_name_234: .asciiz "X-Potion"
ff6vwf_long_item_name_235: .asciiz "Ether"
ff6vwf_long_item_name_236: .asciiz "Hi-Ether"
ff6vwf_long_item_name_237: .asciiz "X-Ether"
ff6vwf_long_item_name_238: .asciiz "Elixir"
ff6vwf_long_item_name_239: .asciiz "Megalixir"
ff6vwf_long_item_name_240: .asciiz "Phoenix Down"
ff6vwf_long_item_name_241: .asciiz "Holy Water"
ff6vwf_long_item_name_242: .asciiz "Antidote"
ff6vwf_long_item_name_243: .asciiz "Eye Drops"
ff6vwf_long_item_name_244: .asciiz "Gold Needle"
ff6vwf_long_item_name_245: .asciiz "Remedy"
ff6vwf_long_item_name_246: .asciiz "Sleeping Bag"
ff6vwf_long_item_name_247: .asciiz "Tent"
ff6vwf_long_item_name_248: .asciiz "Green Cherry"
ff6vwf_long_item_name_249: .asciiz "Magicite Shard"
ff6vwf_long_item_name_250: .asciiz "Super Ball"
ff6vwf_long_item_name_251: .asciiz "Echo Screen"
ff6vwf_long_item_name_252: .asciiz "Smoke Bomb"
ff6vwf_long_item_name_253: .asciiz "Teleport Stone"
ff6vwf_long_item_name_254: .asciiz "Dried Meat"
ff6vwf_long_item_name_255: .asciiz "Empty"

